package com.saldei.hibernate.tables;



/**
 * CargoUsuarioDeiId generated by MyEclipse - Hibernate Tools
 */

public class CargoUsuarioDeiId  implements java.io.Serializable {


    // Fields    
	private static final long serialVersionUID = 1L;
     private Usuario usuario;
     private Integer idCargo;


    // Constructors

    /** default constructor */
    public CargoUsuarioDeiId() {
    }

    
    /** full constructor */
    public CargoUsuarioDeiId(Usuario usuario, Integer idCargo) {
        this.usuario = usuario;
        this.idCargo = idCargo;
    }

   
    // Property accessors

    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public Integer getIdCargo() {
        return this.idCargo;
    }
    
    public void setIdCargo(Integer idCargo) {
        this.idCargo = idCargo;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CargoUsuarioDeiId) ) return false;
		 CargoUsuarioDeiId castOther = ( CargoUsuarioDeiId ) other; 
         
		 return ( (this.getUsuario()==castOther.getUsuario()) || ( this.getUsuario()!=null && castOther.getUsuario()!=null && this.getUsuario().equals(castOther.getUsuario()) ) )
 && ( (this.getIdCargo()==castOther.getIdCargo()) || ( this.getIdCargo()!=null && castOther.getIdCargo()!=null && this.getIdCargo().equals(castOther.getIdCargo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsuario() == null ? 0 : this.getUsuario().hashCode() );
         result = 37 * result + ( getIdCargo() == null ? 0 : this.getIdCargo().hashCode() );
         return result;
   }   





}