package com.saldei.hibernate.tables;

import java.util.HashSet;
import java.util.Set;


/**
 * Carrera generated by MyEclipse - Hibernate Tools
 */

public class Carrera  implements java.io.Serializable {


    // Fields    

     private CarreraId id;
     private Multicode multicode;
     private String nomCarrera;
     private String estCarrera;
     private Set carreraVigencias = new HashSet(0);
     private Set estudianteCarreras = new HashSet(0);


    // Constructors

    /** default constructor */
    public Carrera() {
    }

	/** minimal constructor */
    public Carrera(CarreraId id, String estCarrera) {
        this.id = id;
        this.estCarrera = estCarrera;
    }
    
    /** full constructor */
    public Carrera(CarreraId id, Multicode multicode, String nomCarrera, String estCarrera, Set carreraVigencias, Set estudianteCarreras) {
        this.id = id;
        this.multicode = multicode;
        this.nomCarrera = nomCarrera;
        this.estCarrera = estCarrera;
        this.carreraVigencias = carreraVigencias;
        this.estudianteCarreras = estudianteCarreras;
    }

   
    // Property accessors

    public CarreraId getId() {
        return this.id;
    }
    
    public void setId(CarreraId id) {
        this.id = id;
    }

    public Multicode getMulticode() {
        return this.multicode;
    }
    
    public void setMulticode(Multicode multicode) {
        this.multicode = multicode;
    }

    public String getNomCarrera() {
        return this.nomCarrera;
    }
    
    public void setNomCarrera(String nomCarrera) {
        this.nomCarrera = nomCarrera;
    }

    public String getEstCarrera() {
        return this.estCarrera;
    }
    
    public void setEstCarrera(String estCarrera) {
        this.estCarrera = estCarrera;
    }

    public Set getCarreraVigencias() {
        return this.carreraVigencias;
    }
    
    public void setCarreraVigencias(Set carreraVigencias) {
        this.carreraVigencias = carreraVigencias;
    }

    public Set getEstudianteCarreras() {
        return this.estudianteCarreras;
    }
    
    public void setEstudianteCarreras(Set estudianteCarreras) {
        this.estudianteCarreras = estudianteCarreras;
    }
   








}