package com.saldei.hibernate.tables;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Ciclo generated by MyEclipse - Hibernate Tools
 */

public class Ciclo  implements java.io.Serializable {


    // Fields    

     private String idCiclo;
     private Integer numCiclo;
     private String anyoCiclo;
     private Date fechaIniCiclo;
     private Date fechaFinCiclo;
     private String cicloActivo;
     private String estCiclo;
     private Set materiaCiclos = new HashSet(0);


    // Constructors

    /** default constructor */
    public Ciclo() {
    }

	/** minimal constructor */
    public Ciclo(String idCiclo, Integer numCiclo, String anyoCiclo, Date fechaIniCiclo, Date fechaFinCiclo, String cicloActivo, String estCiclo) {
        this.idCiclo = idCiclo;
        this.numCiclo = numCiclo;
        this.anyoCiclo = anyoCiclo;
        this.fechaIniCiclo = fechaIniCiclo;
        this.fechaFinCiclo = fechaFinCiclo;
        this.cicloActivo = cicloActivo;
        this.estCiclo = estCiclo;
    }
    
    /** full constructor */
    public Ciclo(String idCiclo, Integer numCiclo, String anyoCiclo, Date fechaIniCiclo, Date fechaFinCiclo, String cicloActivo, String estCiclo, Set materiaCiclos) {
        this.idCiclo = idCiclo;
        this.numCiclo = numCiclo;
        this.anyoCiclo = anyoCiclo;
        this.fechaIniCiclo = fechaIniCiclo;
        this.fechaFinCiclo = fechaFinCiclo;
        this.cicloActivo = cicloActivo;
        this.estCiclo = estCiclo;
        this.materiaCiclos = materiaCiclos;
    }

   
    // Property accessors

    public String getIdCiclo() {
        return this.idCiclo;
    }
    
    public void setIdCiclo(String idCiclo) {
        this.idCiclo = idCiclo;
    }

    public Integer getNumCiclo() {
        return this.numCiclo;
    }
    
    public void setNumCiclo(Integer numCiclo) {
        this.numCiclo = numCiclo;
    }

    public String getAnyoCiclo() {
        return this.anyoCiclo;
    }
    
    public void setAnyoCiclo(String anyoCiclo) {
        this.anyoCiclo = anyoCiclo;
    }

    public Date getFechaIniCiclo() {
        return this.fechaIniCiclo;
    }
    
    public void setFechaIniCiclo(Date fechaIniCiclo) {
        this.fechaIniCiclo = fechaIniCiclo;
    }

    public Date getFechaFinCiclo() {
        return this.fechaFinCiclo;
    }
    
    public void setFechaFinCiclo(Date fechaFinCiclo) {
        this.fechaFinCiclo = fechaFinCiclo;
    }

    public String getCicloActivo() {
        return this.cicloActivo;
    }
    
    public void setCicloActivo(String cicloActivo) {
        this.cicloActivo = cicloActivo;
    }

    public String getEstCiclo() {
        return this.estCiclo;
    }
    
    public void setEstCiclo(String estCiclo) {
        this.estCiclo = estCiclo;
    }

    public Set getMateriaCiclos() {
        return this.materiaCiclos;
    }
    
    public void setMateriaCiclos(Set materiaCiclos) {
        this.materiaCiclos = materiaCiclos;
    }
   








}