package com.saldei.hibernate.tables;



/**
 * MateriaInscrita generated by MyEclipse - Hibernate Tools
 */

public class MateriaInscrita  implements java.io.Serializable {


    // Fields    

     private MateriaInscritaId id;
     private String retirada;
     private String estMatInscrita;


    // Constructors

    /** default constructor */
    public MateriaInscrita() {
    }

    
    /** full constructor */
    public MateriaInscrita(MateriaInscritaId id, String retirada, String estMatInscrita) {
        this.id = id;
        this.retirada = retirada;
        this.estMatInscrita = estMatInscrita;
    }

   
    // Property accessors

    public MateriaInscritaId getId() {
        return this.id;
    }
    
    public void setId(MateriaInscritaId id) {
        this.id = id;
    }

    public String getRetirada() {
        return this.retirada;
    }
    
    public void setRetirada(String retirada) {
        this.retirada = retirada;
    }

    public String getEstMatInscrita() {
        return this.estMatInscrita;
    }
    
    public void setEstMatInscrita(String estMatInscrita) {
        this.estMatInscrita = estMatInscrita;
    }
   








}