package com.saldei.hibernate.tables;



/**
 * OpcionPerfil generated by MyEclipse - Hibernate Tools
 */

public class OpcionPerfil  implements java.io.Serializable {


    // Fields    

     private OpcionPerfilId id;


    // Constructors

    /** default constructor */
    public OpcionPerfil() {
    }

    
    /** full constructor */
    public OpcionPerfil(OpcionPerfilId id) {
        this.id = id;
    }

   
    // Property accessors

    public OpcionPerfilId getId() {
        return this.id;
    }
    
    public void setId(OpcionPerfilId id) {
        this.id = id;
    }
   








}