package com.saldei.hibernate.tables;

import java.util.HashSet;
import java.util.Set;


/**
 * Perfil generated by MyEclipse - Hibernate Tools
 */

public class Perfil  implements java.io.Serializable {


    // Fields    

     private Integer idPerfil;
     private String nomPerfil;
     private String descPerfil;
     private String estPerfil;
     private Set usuarioPerfils = new HashSet(0);
     private Set opcionPerfils = new HashSet(0);


    // Constructors

    /** default constructor */
    public Perfil() {
    }

	/** minimal constructor */
    public Perfil(Integer idPerfil, String nomPerfil, String estPerfil) {
        this.idPerfil = idPerfil;
        this.nomPerfil = nomPerfil;
        this.estPerfil = estPerfil;
    }
    
    /** full constructor */
    public Perfil(Integer idPerfil, String nomPerfil, String descPerfil, String estPerfil, Set usuarioPerfils, Set opcionPerfils) {
        this.idPerfil = idPerfil;
        this.nomPerfil = nomPerfil;
        this.descPerfil = descPerfil;
        this.estPerfil = estPerfil;
        this.usuarioPerfils = usuarioPerfils;
        this.opcionPerfils = opcionPerfils;
    }

   
    // Property accessors

    public Integer getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(Integer idPerfil) {
        this.idPerfil = idPerfil;
    }

    public String getNomPerfil() {
        return this.nomPerfil;
    }
    
    public void setNomPerfil(String nomPerfil) {
        this.nomPerfil = nomPerfil;
    }

    public String getDescPerfil() {
        return this.descPerfil;
    }
    
    public void setDescPerfil(String descPerfil) {
        this.descPerfil = descPerfil;
    }

    public String getEstPerfil() {
        return this.estPerfil;
    }
    
    public void setEstPerfil(String estPerfil) {
        this.estPerfil = estPerfil;
    }

    public Set getUsuarioPerfils() {
        return this.usuarioPerfils;
    }
    
    public void setUsuarioPerfils(Set usuarioPerfils) {
        this.usuarioPerfils = usuarioPerfils;
    }

    public Set getOpcionPerfils() {
        return this.opcionPerfils;
    }
    
    public void setOpcionPerfils(Set opcionPerfils) {
        this.opcionPerfils = opcionPerfils;
    }
   








}