package com.saldei.hibernate.tables;

import java.util.HashSet;
import java.util.Set;


/**
 * SolicitudReqMat generated by MyEclipse - Hibernate Tools
 */

public class SolicitudReqMat  implements java.io.Serializable {


    // Fields    

     private Integer idSolicitud;
     private CatedraticoMateria catedraticoMateria;
     private Set reqMats = new HashSet(0);


    // Constructors

    /** default constructor */
    public SolicitudReqMat() {
    }

	/** minimal constructor */
    public SolicitudReqMat(Integer idSolicitud, CatedraticoMateria catedraticoMateria) {
        this.idSolicitud = idSolicitud;
        this.catedraticoMateria = catedraticoMateria;
    }
    
    /** full constructor */
    public SolicitudReqMat(Integer idSolicitud, CatedraticoMateria catedraticoMateria, Set reqMats) {
        this.idSolicitud = idSolicitud;
        this.catedraticoMateria = catedraticoMateria;
        this.reqMats = reqMats;
    }

   
    // Property accessors

    public Integer getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(Integer idSolicitud) {
        this.idSolicitud = idSolicitud;
    }

    public CatedraticoMateria getCatedraticoMateria() {
        return this.catedraticoMateria;
    }
    
    public void setCatedraticoMateria(CatedraticoMateria catedraticoMateria) {
        this.catedraticoMateria = catedraticoMateria;
    }

    public Set getReqMats() {
        return this.reqMats;
    }
    
    public void setReqMats(Set reqMats) {
        this.reqMats = reqMats;
    }
   








}