package com.saldei.hibernate.tables;

import java.util.HashSet;
import java.util.Set;


/**
 * TipoMulticode generated by MyEclipse - Hibernate Tools
 */

public class TipoMulticode  implements java.io.Serializable {


    // Fields    

     private Integer idTipoMulticode;
     private String nomTipoMulticode;
     private String descripcion;
     private String estTipoMulti;
     private Set multicodes = new HashSet(0);


    // Constructors

    /** default constructor */
    public TipoMulticode() {
    }

	/** minimal constructor */
    public TipoMulticode(Integer idTipoMulticode, String nomTipoMulticode, String estTipoMulti) {
        this.idTipoMulticode = idTipoMulticode;
        this.nomTipoMulticode = nomTipoMulticode;
        this.estTipoMulti = estTipoMulti;
    }
    
    /** full constructor */
    public TipoMulticode(Integer idTipoMulticode, String nomTipoMulticode, String descripcion, String estTipoMulti, Set multicodes) {
        this.idTipoMulticode = idTipoMulticode;
        this.nomTipoMulticode = nomTipoMulticode;
        this.descripcion = descripcion;
        this.estTipoMulti = estTipoMulti;
        this.multicodes = multicodes;
    }

   
    // Property accessors

    public Integer getIdTipoMulticode() {
        return this.idTipoMulticode;
    }
    
    public void setIdTipoMulticode(Integer idTipoMulticode) {
        this.idTipoMulticode = idTipoMulticode;
    }

    public String getNomTipoMulticode() {
        return this.nomTipoMulticode;
    }
    
    public void setNomTipoMulticode(String nomTipoMulticode) {
        this.nomTipoMulticode = nomTipoMulticode;
    }

    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getEstTipoMulti() {
        return this.estTipoMulti;
    }
    
    public void setEstTipoMulti(String estTipoMulti) {
        this.estTipoMulti = estTipoMulti;
    }

    public Set getMulticodes() {
        return this.multicodes;
    }
    
    public void setMulticodes(Set multicodes) {
        this.multicodes = multicodes;
    }
   








}