package com.saldei.hibernate.tables;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Usuario generated by MyEclipse - Hibernate Tools
 */

public class Usuario  implements java.io.Serializable {


    // Fields    

     private String idUsuario;
     private String pswUsuario;
     private String primerNom;
     private String primerApe;
     private String nombreRestante;
     private String apellidoRestante;
     private Date fechaNac;
     private String sexo;
     private Integer estadoCivil;
     private String direccionPart;
     private String email;
     private String telefonoCasa;
     private String telefonoCel;
     private String telefonoTrabajo;
     private Date fechaSolicitud;
     private Date fechaResolucion;
     private String dui;
     private String nit;
     private String isss;
     private String nup;
     private String autorizadoPor;
     private String estUsuario;
     private Set cargoUsuarioDeis = new HashSet(0);
     private Set usuarioVigencias = new HashSet(0);
     private Set usuarioPerfils = new HashSet(0);
     private Set usuarioExternos = new HashSet(0);
     private Set usuarioDeis = new HashSet(0);


    // Constructors

    /** default constructor */
    public Usuario() {
    }

	/** minimal constructor */
    public Usuario(String idUsuario, String pswUsuario, String primerNom, String primerApe, String sexo, Integer estadoCivil, String email, String estUsuario) {
        this.idUsuario = idUsuario;
        this.pswUsuario = pswUsuario;
        this.primerNom = primerNom;
        this.primerApe = primerApe;
        this.sexo = sexo;
        this.estadoCivil = estadoCivil;
        this.email = email;
        this.estUsuario = estUsuario;
    }
    
    /** full constructor */
    public Usuario(String idUsuario, String pswUsuario, String primerNom, String primerApe, String nombreRestante, String apellidoRestante, Date fechaNac, String sexo, Integer estadoCivil, String direccionPart, String email, String telefonoCasa, String telefonoCel, String telefonoTrabajo, Date fechaSolicitud, Date fechaResolucion, String dui, String nit, String isss, String nup, String autorizadoPor, String estUsuario, Set cargoUsuarioDeis, Set usuarioVigencias, Set usuarioPerfils, Set usuarioExternos, Set usuarioDeis) {
        this.idUsuario = idUsuario;
        this.pswUsuario = pswUsuario;
        this.primerNom = primerNom;
        this.primerApe = primerApe;
        this.nombreRestante = nombreRestante;
        this.apellidoRestante = apellidoRestante;
        this.fechaNac = fechaNac;
        this.sexo = sexo;
        this.estadoCivil = estadoCivil;
        this.direccionPart = direccionPart;
        this.email = email;
        this.telefonoCasa = telefonoCasa;
        this.telefonoCel = telefonoCel;
        this.telefonoTrabajo = telefonoTrabajo;
        this.fechaSolicitud = fechaSolicitud;
        this.fechaResolucion = fechaResolucion;
        this.dui = dui;
        this.nit = nit;
        this.isss = isss;
        this.nup = nup;
        this.autorizadoPor = autorizadoPor;
        this.estUsuario = estUsuario;
        this.cargoUsuarioDeis = cargoUsuarioDeis;
        this.usuarioVigencias = usuarioVigencias;
        this.usuarioPerfils = usuarioPerfils;
        this.usuarioExternos = usuarioExternos;
        this.usuarioDeis = usuarioDeis;
    }

   
    // Property accessors

    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }

    public String getPswUsuario() {
        return this.pswUsuario;
    }
    
    public void setPswUsuario(String pswUsuario) {
        this.pswUsuario = pswUsuario;
    }

    public String getPrimerNom() {
        return this.primerNom;
    }
    
    public void setPrimerNom(String primerNom) {
        this.primerNom = primerNom;
    }

    public String getPrimerApe() {
        return this.primerApe;
    }
    
    public void setPrimerApe(String primerApe) {
        this.primerApe = primerApe;
    }

    public String getNombreRestante() {
        return this.nombreRestante;
    }
    
    public void setNombreRestante(String nombreRestante) {
        this.nombreRestante = nombreRestante;
    }

    public String getApellidoRestante() {
        return this.apellidoRestante;
    }
    
    public void setApellidoRestante(String apellidoRestante) {
        this.apellidoRestante = apellidoRestante;
    }

    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }

    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    public Integer getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(Integer estadoCivil) {
        this.estadoCivil = estadoCivil;
    }

    public String getDireccionPart() {
        return this.direccionPart;
    }
    
    public void setDireccionPart(String direccionPart) {
        this.direccionPart = direccionPart;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getTelefonoCasa() {
        return this.telefonoCasa;
    }
    
    public void setTelefonoCasa(String telefonoCasa) {
        this.telefonoCasa = telefonoCasa;
    }

    public String getTelefonoCel() {
        return this.telefonoCel;
    }
    
    public void setTelefonoCel(String telefonoCel) {
        this.telefonoCel = telefonoCel;
    }

    public String getTelefonoTrabajo() {
        return this.telefonoTrabajo;
    }
    
    public void setTelefonoTrabajo(String telefonoTrabajo) {
        this.telefonoTrabajo = telefonoTrabajo;
    }

    public Date getFechaSolicitud() {
        return this.fechaSolicitud;
    }
    
    public void setFechaSolicitud(Date fechaSolicitud) {
        this.fechaSolicitud = fechaSolicitud;
    }

    public Date getFechaResolucion() {
        return this.fechaResolucion;
    }
    
    public void setFechaResolucion(Date fechaResolucion) {
        this.fechaResolucion = fechaResolucion;
    }

    public String getDui() {
        return this.dui;
    }
    
    public void setDui(String dui) {
        this.dui = dui;
    }

    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }

    public String getIsss() {
        return this.isss;
    }
    
    public void setIsss(String isss) {
        this.isss = isss;
    }

    public String getNup() {
        return this.nup;
    }
    
    public void setNup(String nup) {
        this.nup = nup;
    }

    public String getAutorizadoPor() {
        return this.autorizadoPor;
    }
    
    public void setAutorizadoPor(String autorizadoPor) {
        this.autorizadoPor = autorizadoPor;
    }

    public String getEstUsuario() {
        return this.estUsuario;
    }
    
    public void setEstUsuario(String estUsuario) {
        this.estUsuario = estUsuario;
    }

    public Set getCargoUsuarioDeis() {
        return this.cargoUsuarioDeis;
    }
    
    public void setCargoUsuarioDeis(Set cargoUsuarioDeis) {
        this.cargoUsuarioDeis = cargoUsuarioDeis;
    }

    public Set getUsuarioVigencias() {
        return this.usuarioVigencias;
    }
    
    public void setUsuarioVigencias(Set usuarioVigencias) {
        this.usuarioVigencias = usuarioVigencias;
    }

    public Set getUsuarioPerfils() {
        return this.usuarioPerfils;
    }
    
    public void setUsuarioPerfils(Set usuarioPerfils) {
        this.usuarioPerfils = usuarioPerfils;
    }

    public Set getUsuarioExternos() {
        return this.usuarioExternos;
    }
    
    public void setUsuarioExternos(Set usuarioExternos) {
        this.usuarioExternos = usuarioExternos;
    }

    public Set getUsuarioDeis() {
        return this.usuarioDeis;
    }
    
    public void setUsuarioDeis(Set usuarioDeis) {
        this.usuarioDeis = usuarioDeis;
    }
   








}