package com.saldei.hibernate.tables;

import java.util.Date;


/**
 * UsuarioVigencia generated by MyEclipse - Hibernate Tools
 */

public class UsuarioVigencia  implements java.io.Serializable {


    // Fields    

     private UsuarioVigenciaId id;
     private Date fechaFin;


    // Constructors

    /** default constructor */
    public UsuarioVigencia() {
    }

    
    /** full constructor */
    public UsuarioVigencia(UsuarioVigenciaId id, Date fechaFin) {
        this.id = id;
        this.fechaFin = fechaFin;
    }

   
    // Property accessors

    public UsuarioVigenciaId getId() {
        return this.id;
    }
    
    public void setId(UsuarioVigenciaId id) {
        this.id = id;
    }

    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
   








}