package com.saldei.hibernate.tables;

import java.util.Date;


/**
 * UsuarioVigenciaId generated by MyEclipse - Hibernate Tools
 */

public class UsuarioVigenciaId  implements java.io.Serializable {


    // Fields    

     private Usuario usuario;
     private Date fechaIni;


    // Constructors

    /** default constructor */
    public UsuarioVigenciaId() {
    }

    
    /** full constructor */
    public UsuarioVigenciaId(Usuario usuario, Date fechaIni) {
        this.usuario = usuario;
        this.fechaIni = fechaIni;
    }

   
    // Property accessors

    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public Date getFechaIni() {
        return this.fechaIni;
    }
    
    public void setFechaIni(Date fechaIni) {
        this.fechaIni = fechaIni;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuarioVigenciaId) ) return false;
		 UsuarioVigenciaId castOther = ( UsuarioVigenciaId ) other; 
         
		 return ( (this.getUsuario()==castOther.getUsuario()) || ( this.getUsuario()!=null && castOther.getUsuario()!=null && this.getUsuario().equals(castOther.getUsuario()) ) )
 && ( (this.getFechaIni()==castOther.getFechaIni()) || ( this.getFechaIni()!=null && castOther.getFechaIni()!=null && this.getFechaIni().equals(castOther.getFechaIni()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsuario() == null ? 0 : this.getUsuario().hashCode() );
         result = 37 * result + ( getFechaIni() == null ? 0 : this.getFechaIni().hashCode() );
         return result;
   }   





}