package com.saldei.hibernate.tables;

// Generated by MyEclipse Persistence Tools

/**
 * UsuarioTitulo generated by MyEclipse Persistence Tools
 */
public class UsuarioTitulo extends AbstractUsuarioTitulo implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public UsuarioTitulo() {
	}

	/**
	 * @param usuarioDei
	 * @param titulo
	 * @param abvTitulo
	 * @param porDefecto
	 */
	public UsuarioTitulo(UsuarioDei usuarioDei, String titulo,
			String abvTitulo, String porDefecto) {
		super(usuarioDei, titulo, abvTitulo, porDefecto);
		// TODO Auto-generated constructor stub
	}

	/**
	 * @param usuarioDei
	 */
	public UsuarioTitulo(UsuarioDei usuarioDei) {
		super(usuarioDei);
		// TODO Auto-generated constructor stub
	}


}
