/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.saldei.web.form.activos;

import java.util.Date;
import java.util.ResourceBundle;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import com.saldei.hibernate.tables.activos.ActActivo;
import com.saldei.hibernate.tables.activos.ActEstadoActivo;
import com.saldei.hibernate.tables.activos.ActMotivoBaja;
import com.saldei.hibernate.tables.activos.ActTipoUnidad;
import com.saldei.hibernate.tables.activos.ActUnidad;

/** 
 * MyEclipse Struts
 * Creation date: 06-13-2009
 * 
 * XDoclet definition:
 * @struts.form name="activoForm"
 */
public class ActivoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	private String recursoDesc;
	private String estadoDescr;
	private String estadoShow;
	private Integer codEstadoActivo;
	private String estadoFisico;

	
	/** actActivo property */
	private ActActivo actActivo = new ActActivo(new ActUnidad(new ActTipoUnidad()),new ActMotivoBaja(), new ActEstadoActivo()) ;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public void validate(ActionMapping mapping,
			HttpServletRequest request, ActionErrors errors) {
		// TODO Auto-generated method stub
		String accion = request.getParameter("accion");
		accion = (accion==null)?"":accion;
		
		ResourceBundle mensajes = ResourceBundle.getBundle("com.saldei.web.ApplicationResources");
		if(!accion.equals(mensajes.getString("opc.cancel")) && !accion.equals(mensajes.getString("opc.find"))){			
			if(this.getCodRecurso() == null || this.getCodRecurso().trim().equals("")){
				errors.add("activo.recurso.requerido", new ActionError("activo.recurso.requerido"));
			}
			
			if(this.getCodUnidad() == null || this.getCodUnidad().trim().equals("")){
				errors.add("activo.unidad.requerido", new ActionError("activo.unidad.requerido"));
			}
			
			if(this.getNumSerie() == null || this.getNumSerie().trim().equals("")){
				errors.add("activo.serie.requerido", new ActionError("activo.serie.requerido"));
			}
			
			if(this.getCodEstadoActivo() == null || this.getCodEstadoActivo()==0){
				errors.add("activo.estado.requerido", new ActionError("activo.estado.requerido"));
			}
		}				
		
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		actActivo = new ActActivo(new ActUnidad(new ActTipoUnidad()),new ActMotivoBaja(), new ActEstadoActivo()) ;
		this.recursoDesc = null;
		this.estadoShow="";
		this.estadoFisico="";
		}

	/** 
	 * Returns the actActivo.
	 * @return ActActivo
	 */
	public ActActivo getActActivo() {
		return actActivo;
	}

	/** 
	 * Set the actActivo.
	 * @param actActivo The actActivo to set
	 */
	public void setActActivo(ActActivo actActivo) {
		this.actActivo = actActivo;
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#getActMotivoBaja()
	 */
	public ActMotivoBaja getActMotivoBaja() {
		return actActivo.getActMotivoBaja();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#getActUnidad()
	 */
	public ActUnidad getActUnidad() {
		return actActivo.getActUnidad();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#getCodActivo()
	 */


	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#getCodAltUca()
	 */
	public String getCodAltUca() {
		return actActivo.getCodAltUca();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#getCodRecurso()
	 */
	public String getCodRecurso() {
		return actActivo.getCodRecurso();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#getCreadoPor()
	 */
	public String getCreadoPor() {
		return actActivo.getCreadoPor();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#getEstado()
	 */
	public String getEstado() {
		return actActivo.getEstado();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#getFechaBaja()
	 */
	public Date getFechaBaja() {
		return actActivo.getFechaBaja();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#getFechaCreacion()
	 */
	public Date getFechaCreacion() {
		return actActivo.getFechaCreacion();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#getMotivo()
	 */
	public String getMotivo() {
		return actActivo.getMotivo();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#getNumSerie()
	 */
	public String getNumSerie() {
		return actActivo.getNumSerie();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#getUsuarioBaja()
	 */
	public String getUsuarioBaja() {
		return actActivo.getUsuarioBaja();
	}

	/**
	 * @param actMotivoBaja
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#setActMotivoBaja(com.saldei.hibernate.tables.activos.ActMotivoBaja)
	 */
	public void setActMotivoBaja(ActMotivoBaja actMotivoBaja) {
		actActivo.setActMotivoBaja(actMotivoBaja);
	}

	/**
	 * @param actUnidad
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#setActUnidad(com.saldei.hibernate.tables.activos.ActUnidad)
	 */
	public void setActUnidad(ActUnidad actUnidad) {
		actActivo.setActUnidad(actUnidad);
	}

	/**
	 * @param codActivo
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#setCodActivo(java.lang.Integer)
	 */

	/**
	 * @param codAltUca
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#setCodAltUca(java.lang.String)
	 */
	public void setCodAltUca(String codAltUca) {
		actActivo.setCodAltUca(codAltUca);
	}

	/**
	 * @param codRecurso
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#setCodRecurso(java.lang.String)
	 */
	public void setCodRecurso(String codRecurso) {
		actActivo.setCodRecurso(codRecurso);
	}

	/**
	 * @param creadoPor
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#setCreadoPor(java.lang.String)
	 */
	public void setCreadoPor(String creadoPor) {
		actActivo.setCreadoPor(creadoPor);
	}

	/**
	 * @param estado
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#setEstado(java.lang.String)
	 */
	public void setEstado(String estado) {
		actActivo.setEstado(estado);
	}

	/**
	 * @param fechaBaja
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#setFechaBaja(java.util.Date)
	 */
	public void setFechaBaja(Date fechaBaja) {
		actActivo.setFechaBaja(fechaBaja);
	}

	/**
	 * @param fechaCreacion
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#setFechaCreacion(java.util.Date)
	 */
	public void setFechaCreacion(Date fechaCreacion) {
		actActivo.setFechaCreacion(fechaCreacion);
	}

	/**
	 * @param motivo
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#setMotivo(java.lang.String)
	 */
	public void setMotivo(String motivo) {
		actActivo.setMotivo(motivo);
	}

	/**
	 * @param numSerie
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#setNumSerie(java.lang.String)
	 */
	public void setNumSerie(String numSerie) {
		actActivo.setNumSerie(numSerie);
	}

	/**
	 * @param usuarioBaja
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#setUsuarioBaja(java.lang.String)
	 */
	public void setUsuarioBaja(String usuarioBaja) {
		actActivo.setUsuarioBaja(usuarioBaja);
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActMotivoBaja#getCodBaja()
	 */
	public Integer getCodBaja() {
		return this.actActivo.getActMotivoBaja().getCodBaja();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActMotivoBaja#getDescripcion()
	 */
	public String getMotivoBajaDesc() {
		return this.actActivo.getActMotivoBaja().getDescripcion();
	}

	/**
	 * @param codBaja
	 * @see com.saldei.hibernate.tables.activos.AbstractActMotivoBaja#setCodBaja(java.lang.Integer)
	 */
	public void setCodBaja(Integer codBaja) {
		this.actActivo.getActMotivoBaja().setCodBaja(codBaja);
	}

	/**
	 * @param descripcion
	 * @see com.saldei.hibernate.tables.activos.AbstractActMotivoBaja#setDescripcion(java.lang.String)
	 */
	public void setMotivoBajaDesc(String motivoBajaDesc) {
		this.actActivo.getActMotivoBaja().setDescripcion(motivoBajaDesc);
	}

	/**
	 * @return 
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActUnidad#getActTipoUnidad()
	 */
	public  Integer getCodTipoUnidad() {
		return this.actActivo.getActUnidad().getActTipoUnidad().getCodTipoUnidad();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActUnidad#getCodUnidad()
	 */
	public String getCodUnidad() {
		if (this.actActivo.getActUnidad().getCodUnidad() != null)
			return String.valueOf(this.actActivo.getActUnidad().getCodUnidad());
		else 
			return "";
	}

	/**
	 * @param actTipoUnidad
	 * @see com.saldei.hibernate.tables.activos.AbstractActUnidad#setActTipoUnidad(com.saldei.hibernate.tables.activos.ActTipoUnidad)
	 */
	public void setCodTipoUnidad(Integer codTipoUnidad) {
		this.actActivo.getActUnidad().getActTipoUnidad().setCodTipoUnidad(codTipoUnidad);
	}

	/**
	 * @param codUnidad
	 * @see com.saldei.hibernate.tables.activos.AbstractActUnidad#setCodUnidad(java.lang.Integer)
	 */
	public void setCodUnidad(String codUnidad) {
		if(codUnidad != null && !codUnidad.trim().equals(""))
			this.actActivo.getActUnidad().setCodUnidad(Integer.valueOf(codUnidad));
	}

	/**
	 * @return the recursoDesc
	 */
	public String getRecursoDesc() {
		return recursoDesc;
	}

	/**
	 * @param recursoDesc the recursoDesc to set
	 */
	public void setRecursoDesc(String recursoDesc) {
		this.recursoDesc = recursoDesc;
	}
	
	/**
	 * @param unidadDesc	 
	 */
	public String getUnidadDesc() {
		return this.actActivo.getActUnidad().getDescripcion();
	}
	
	
	/**
	 * @param unidadDesc
	 * @see com.saldei.hibernate.tables.activos.AbstractActMotivoBaja#setDescripcion(java.lang.String)
	 */
	public void setUnidadDesc(String unidadDesc) {
		this.actActivo.getActUnidad().setDescripcion(unidadDesc);
	}

	public String getEstadoDescr() {
		return estadoDescr;
	}

	public void setEstadoDescr(String estadoDescr) {
		this.estadoDescr = estadoDescr;
	}

	public String getEstadoShow() {
		return estadoShow;
	}

	public void setEstadoShow(String estadoShow) {
		this.estadoShow = estadoShow;
	}

	public ActEstadoActivo getActEstadoActivo() {
		return actActivo.getActEstadoActivo();
	}

	public void setActEstadoActivo(ActEstadoActivo actEstadoActivo) {
		actActivo.setActEstadoActivo(actEstadoActivo);
	}

	public Integer getCodEstadoActivo() {
		return actActivo.getActEstadoActivo().getCodEstado();
	}

	public void setCodEstadoActivo(Integer codEstado) {
		this.actActivo.getActEstadoActivo().setCodEstado(codEstado);
	}

	public String getEstadoFisico() {
		return estadoFisico;
	}

	public void setEstadoFisico(String estadoFisico) {
		this.estadoFisico = estadoFisico;
	}

	public Integer getCodActivo() {
		return actActivo.getCodActivo();
	}

	public void setCodActivo(Integer codActivo) {
		actActivo.setCodActivo(codActivo);
	}
	
	
}