/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.saldei.web.form.activos;

import java.util.ResourceBundle;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import com.saldei.hibernate.tables.activos.ActCotizacion;
import com.saldei.hibernate.tables.activos.ActCotizacionId;
import com.saldei.hibernate.tables.activos.ActDetCotizacion;
import com.saldei.hibernate.tables.activos.ActDetCotizacionId;
import com.saldei.hibernate.tables.activos.ActProveedor;
import com.saldei.hibernate.tables.activos.ActSolicitud;
import com.saldei.hibernate.tables.activos.ActSolicitudId;
import com.saldei.hibernate.tables.inventario.InvRecurso;
import com.saldei.util.hibernate.dao.HibernateSessionFactory;
import com.saldei.web.services.administracion.ParametroServices;

/** 
 * MyEclipse Struts
 * Creation date: 07-01-2009
 * 
 * XDoclet definition:
 * @struts.form name="cotizacionDetForm"
 */
public class CotizacionDetForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** actDetCotizacion property */
	private ActDetCotizacion actDetCotizacion =  new ActDetCotizacion(new ActDetCotizacionId(new ActCotizacion(new ActCotizacionId(new ActSolicitud(new ActSolicitudId()),null), new ActProveedor()),new InvRecurso()));	
	private String nombreRecurso;	
	private String pumoney;
	private String momoney;
	private String tasaIva;
	
	/*
	 * Generated Methods
	 */

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActCotizacion#getIva()
	 */
	public String getIva() {
		String valorIVA = this.actDetCotizacion.getId().getActCotizacion().getIva();
		if(valorIVA != null && valorIVA.equals("S"))
			return "SI";
		else 
			return "NO";
	}

	/**
	 * @param iva
	 * @see com.saldei.hibernate.tables.activos.AbstractActCotizacion#setIva(java.lang.String)
	 */
	public void setIva(String iva) {
		this.actDetCotizacion.getId().getActCotizacion().setIva(iva);
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public void  validate(ActionMapping mapping,
			HttpServletRequest request,ActionErrors errors) {
		// TODO Auto-generated method stub
		String accion = request.getParameter("accion");
		accion = (accion==null)?"":accion;
		
		ResourceBundle mensajes = ResourceBundle.getBundle("com.saldei.web.ApplicationResources");
	
		if(!accion.equals(mensajes.getString("opc.cancel")) && !accion.equals(mensajes.getString("opc.find"))){
			if(this.getNombreRecurso() == null || this.getCodRecurso().trim().equals("")){
				errors.add("cotizacionDet.recurso.requerido", new ActionError("cotizacionDet.recurso.requerido"));
			}
			if(this.getPrecioUnitario() == 0.0){
				errors.add("cotizacionDet.precioUnitario.requerido", new ActionError("cotizacionDet.precioUnitario.requerido"));
			}
			if(this.getCantidad() == null || this.getCantidad() == 0){
				errors.add("cotizacionDet.cantidad.requerido", new ActionError("cotizacionDet.cantidad.requerido"));
			}
		}
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		this.actDetCotizacion =  new ActDetCotizacion(new ActDetCotizacionId(new ActCotizacion(new ActCotizacionId(new ActSolicitud(new ActSolicitudId()),null), new ActProveedor()),new InvRecurso()));
		this.nombreRecurso = null;
	}

	/** 
	 * Returns the actDetCotizacion.
	 * @return ActDetCotizacion
	 */
	public ActDetCotizacion getActDetCotizacion() {
		return actDetCotizacion;
	}

	/** 
	 * Set the actDetCotizacion.
	 * @param actDetCotizacion The actDetCotizacion to set
	 */
	public void setActDetCotizacion(ActDetCotizacion actDetCotizacion) {
		this.actDetCotizacion = actDetCotizacion;
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActDetCotizacion#getCantidad()
	 */
	public Integer getCantidad() {
		return actDetCotizacion.getCantidad();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActDetCotizacion#getId()
	 */
	public ActDetCotizacionId getId() {
		return actDetCotizacion.getId();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActDetCotizacion#getPrecioUnitario()
	 */
	public double getPrecioUnitario() {
		return actDetCotizacion.getPrecioUnitario();
	}

	/**
	 * @param cantidad
	 * @see com.saldei.hibernate.tables.activos.AbstractActDetCotizacion#setCantidad(java.lang.Integer)
	 */
	public void setCantidad(Integer cantidad) {
		actDetCotizacion.setCantidad(cantidad);
	}

	/**
	 * @param id
	 * @see com.saldei.hibernate.tables.activos.AbstractActDetCotizacion#setId(com.saldei.hibernate.tables.activos.ActDetCotizacionId)
	 */
	public void setId(ActDetCotizacionId id) {
		actDetCotizacion.setId(id);
	}

	/**
	 * @param precioUnitario
	 * @see com.saldei.hibernate.tables.activos.AbstractActDetCotizacion#setPrecioUnitario(double)
	 */
	public void setPrecioUnitario(double precioUnitario) {
		actDetCotizacion.setPrecioUnitario(precioUnitario);
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActCotizacionId#getCodCotizacion()
	 */
	public String getCodCotizacion() {
		if(this.actDetCotizacion.getId().getActCotizacion().getId().getCodCotizacion() != null)
			return String.valueOf(this.actDetCotizacion.getId().getActCotizacion().getId().getCodCotizacion());
		else return "";
	}

	/**
	 * @param codCotizacion
	 * @see com.saldei.hibernate.tables.activos.AbstractActCotizacionId#setCodCotizacion(java.lang.Integer)
	 */
	public void setCodCotizacion(String codCotizacion) {
		if (codCotizacion != null && !codCotizacion.trim().equals(""))
			this.actDetCotizacion.getId().getActCotizacion().getId().setCodCotizacion(Integer.valueOf(codCotizacion));
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitudId#getCodSolicitud()
	 */
	public String getCodSolicitud() {
		if(this.actDetCotizacion.getId().getActCotizacion().getId().getActSolicitud().getId().getCodSolicitud()!= null)
			return String.valueOf(this.actDetCotizacion.getId().getActCotizacion().getId().getActSolicitud().getId().getCodSolicitud());
		else return "";
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitudId#getTipoSolicitud()
	 */
	public String getTipoSolicitud() {
		return this.actDetCotizacion.getId().getActCotizacion().getId().getActSolicitud().getId().getTipoSolicitud();
	}

	/**
	 * @param codSolicitud
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitudId#setCodSolicitud(java.lang.Integer)
	 */
	public void setCodSolicitud(String codSolicitud) {
		if(codSolicitud != null && !codSolicitud.trim().equals(""))
			this.actDetCotizacion.getId().getActCotizacion().getId().getActSolicitud().getId().setCodSolicitud(Integer.valueOf(codSolicitud));
	}

	/**
	 * @param tipoSolicitud
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitudId#setTipoSolicitud(java.lang.String)
	 */
	public void setTipoSolicitud(String tipoSolicitud) {
		this.actDetCotizacion.getId().getActCotizacion().getId().getActSolicitud().getId().setTipoSolicitud(tipoSolicitud);
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActProveedor#getCodProveedor()
	 */
	public String getCodProveedor() {
		return this.actDetCotizacion.getId().getActCotizacion().getActProveedor().getCodProveedor();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActProveedor#getNombre()
	 */
	public String getNombreProveedor() {
		return this.actDetCotizacion.getId().getActCotizacion().getActProveedor().getNombre();
	}

	/**
	 * @param codProveedor
	 * @see com.saldei.hibernate.tables.activos.AbstractActProveedor#setCodProveedor(java.lang.String)
	 */
	public void setCodProveedor(String codProveedor) {
		this.actDetCotizacion.getId().getActCotizacion().getActProveedor().setCodProveedor(codProveedor);
	}

	/**
	 * @param nombre
	 * @see com.saldei.hibernate.tables.activos.AbstractActProveedor#setNombre(java.lang.String)
	 */
	public void setNombreProveedor(String nombreProveedor) {
		this.actDetCotizacion.getId().getActCotizacion().getActProveedor().setNombre(nombreProveedor);
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.inventario.AbstractInvRecurso#getCodRecurso()
	 */
	public String getCodRecurso() {
		return this.actDetCotizacion.getId().getInvRecurso().getCodRecurso();
	}


	/**
	 * @param codRecurso
	 * @see com.saldei.hibernate.tables.inventario.AbstractInvRecurso#setCodRecurso(java.lang.String)
	 */
	public void setCodRecurso(String codRecurso) {
		this.actDetCotizacion.getId().getInvRecurso().setCodRecurso(codRecurso);
	}

	/**
	 * @return the nombreRecurso
	 */
	public String getNombreRecurso() {
		return this.actDetCotizacion.getId().getInvRecurso().getNombre();
	}

	/**
	 * @param nombreRecurso the nombreRecurso to set
	 */
	public void setNombreRecurso(String nombreRecurso) {
		this.actDetCotizacion.getId().getInvRecurso().setNombre(nombreRecurso);
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#getEstado()
	 */
	public String getEstado() {
		return this.actDetCotizacion.getId().getActCotizacion().getId().getActSolicitud().getEstado();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.ActSolicitud#getEstadoDesc()
	 */
	public String getEstadoDesc() {
		return this.actDetCotizacion.getId().getActCotizacion().getId().getActSolicitud().getEstadoDesc();
	}

	/**
	 * @param estado
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#setEstado(java.lang.String)
	 */
	public void setEstado(String estado) {
		this.actDetCotizacion.getId().getActCotizacion().getId().getActSolicitud().setEstado(estado);
	}

	public String getPumoney() {
		return pumoney;
	}

	public void setPumoney(String pumoney) {
		this.pumoney = pumoney;
	}

	public String getMomoney() {
		return momoney;
	}

	public void setMomoney(String momoney) {
		this.momoney = momoney;
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActCotizacion#getComentario()
	 */
	public String getComentario() {
		return actDetCotizacion.getId().getActCotizacion().getComentario();
	}

	/**
	 * @param comentario
	 * @see com.saldei.hibernate.tables.activos.AbstractActCotizacion#setComentario(java.lang.String)
	 */
	public void setComentario(String comentario) {
		actDetCotizacion.getId().getActCotizacion().setComentario(comentario);
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#getCodBodega()
	 */
	public Integer getCodBodega() {
		return actDetCotizacion.getId().getActCotizacion().getId().getActSolicitud().getCodBodega();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.ActSolicitud#getDesBodega()
	 */
	public String getDesBodega() {
		return actDetCotizacion.getId().getActCotizacion().getId().getActSolicitud().getDesBodega();
	}

	/**
	 * @param codBodega
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#setCodBodega(java.lang.Integer)
	 */
	public void setCodBodega(Integer codBodega) {
		actDetCotizacion.getId().getActCotizacion().getId().getActSolicitud().setCodBodega(codBodega);
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActDetCotizacion#getPrecioUnitarioIva()
	 */
	public double getPrecioUnitarioIva() {
		return actDetCotizacion.getPrecioUnitarioIva();
	}
	
	
	public String getTasaIva() {
		ParametroServices parametroServices = new ParametroServices();		
		this.tasaIva = parametroServices.valorParametro("IVA");
		HibernateSessionFactory.getSession().close();
		return this.tasaIva;
	}
	
	public void setTasaIva(String tasaIva) {			
		this.tasaIva = tasaIva;
		
	}

	/**
	 * @param precioUnitarioIva
	 * @see com.saldei.hibernate.tables.activos.AbstractActDetCotizacion#setPrecioUnitarioIva(long)
	 */
	public void setPrecioUnitarioIva(double precioUnitarioIva) {
		actDetCotizacion.setPrecioUnitarioIva(precioUnitarioIva);
	}



}