/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.saldei.web.action.inventario;

import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessages;

import com.saldei.hibernate.tables.activos.ActSolicitudDAO;
import com.saldei.util.hibernate.dao.HibernateSessionFactory;
import com.saldei.web.action.BaseAction;
import com.saldei.web.form.activos.AprSolDescActForm;
import com.saldei.web.form.inventario.AprSolicitudAbaForm;

/** 
 * MyEclipse Struts
 * Creation date: 07-12-2009
 * 
 * XDoclet definition:
 * @struts.action path="/aprSolicitudAbaAction" name="aprSolicitudAbaForm" input="/html/inventario/aprSolicitudAba.jsp" parameter="accion" scope="request"
 * @struts.action-forward name="updateFail" path="/html/inventario/aprSolicitud.jsp"
 * @struts.action-forward name="back" path="/aprSolicitudAbaAction.do?accion=Find"
 * @struts.action-forward name="success" path="/html/inventario/aprSolicitudAba.jsp?accion="
 */
public class AprSolicitudAbaAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@Override
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public ActionForward insert(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public ActionForward update(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub
		return null;
	}
	

	public ActionForward find(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception,
			ServletException {		
		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;
		String cod;
		List data;
		
		AprSolicitudAbaForm aprSolicitudAbaForm = (AprSolicitudAbaForm) form;
		ActSolicitudDAO actSolicitudDAO = new ActSolicitudDAO();
		cod=(String) session.getAttribute("user");
		try {
			/*
			if(aprReqRecursoForm.getMostrarHistorico()!=null && aprReqRecursoForm.getMostrarHistorico().equals("S"))
				data = actSolicitudDAO.findAllReq("S");
			else
				data = actSolicitudDAO.findAllReq("N");
				request.setAttribute("listSolicitud", data);
				*/
			if(aprSolicitudAbaForm.getMostrarHistorico()!=null && aprSolicitudAbaForm.getMostrarHistorico().equals("S"))
				data = actSolicitudDAO.findAprSolAba("S");
			else
				data = actSolicitudDAO.findAprSolAba("N");
				request.setAttribute("listSolAba", data);
		    
			
			//data = actSolicitudDAO.findAprSolAba();
		   // request.setAttribute("listSolAba", data);
		  if(!isFLAG_UPDATE()){
				aprSolicitudAbaForm.reset(mapping, request);
			}else{
				setFLAG_UPDATE(false);
			}			
			
		} catch (Exception e) {
			e.printStackTrace();			
			// TODO: handle exception
		}finally{
			HibernateSessionFactory.getSession().close();
		} 	
		return mapping.findForward(target);
	}
}