/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.saldei.web.action.activos;

import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessages;
import org.hibernate.exception.ConstraintViolationException;

import com.saldei.hibernate.tables.activos.ActMotivoBajaDAO;
import com.saldei.util.hibernate.dao.HibernateSessionFactory;
import com.saldei.web.action.BaseAction;
import com.saldei.web.form.activos.MotivoBajaForm;

/**
 * MyEclipse Struts Creation date: 06-09-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/motivoBajaAction" name="motivoBajaForm"
 *                input="/html/activos/motivoBaja.jsp" parameter="accion"
 *                scope="request"
 * @struts.action-forward name="updateFail" path="/html/activos/motivoBaja.jsp"
 * @struts.action-forward name="back" path="/html/activos/motivoBaja.jsp"
 * @struts.action-forward name="success" path="/html/activos/motivoBaja.jsp"
 */
public class MotivoBajaAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@SuppressWarnings("deprecation")
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub
		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;

		MotivoBajaForm motivoBajaForm = (MotivoBajaForm) form;
		ActMotivoBajaDAO actMotivoBajaDAO = new ActMotivoBajaDAO();

		try {

			actMotivoBajaDAO.delete(motivoBajaForm.getActMotivoBaja());
			HibernateSessionFactory.getSession().beginTransaction().commit();
			errors.add("moba.mensaje.exito", new ActionError(
					"moba.mensaje.exito.delete"));

		} catch (ConstraintViolationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			errors.add("moba.mensajeError.error", new ActionError(
					"moba.mensajeError.error.nodelete"));
			HibernateSessionFactory.getSession().beginTransaction().rollback();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			HibernateSessionFactory.getSession().beginTransaction().rollback();
		} finally {
			HibernateSessionFactory.getSession().close();
		}

		find(mapping, form, request, response);
		return mapping.findForward(target);
	}

	@SuppressWarnings("deprecation")
	public ActionForward insert(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub

		MotivoBajaForm motivoBajaForm = (MotivoBajaForm) form;
		ActMotivoBajaDAO actMotivoBajaDAO = new ActMotivoBajaDAO();

		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;

		try {
			motivoBajaForm.validate(mapping, request, errors);
			if (errors.isEmpty()) {
				actMotivoBajaDAO.save(motivoBajaForm.getActMotivoBaja());
				HibernateSessionFactory.getSession().beginTransaction()
						.commit();
				errors.add("moba.mensaje.exito", new ActionError(
						"moba.mensaje.exito.insert"));
			} else {
				setFLAG_UPDATE(true);
			}
		} catch (Exception e) {
			e.printStackTrace();
			HibernateSessionFactory.getSession().beginTransaction().rollback();
			// TODO: handle exception
		} finally {
			HibernateSessionFactory.getSession().close();
		}

		find(mapping, form, request, response);
		return mapping.findForward(target);
	}

	public ActionForward update(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub

		MotivoBajaForm motivoBajaForm = (MotivoBajaForm) form;
		ActMotivoBajaDAO actMotivoBajaDAO = new ActMotivoBajaDAO();

		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;

		try {
			motivoBajaForm.validate(mapping, request, errors);
			if (errors.isEmpty()) {
				actMotivoBajaDAO.merge(motivoBajaForm.getActMotivoBaja());
				HibernateSessionFactory.getSession().beginTransaction()
						.commit();
				errors.add("moba.mensaje.exito", new ActionError(
						"moba.mensaje.exito.update"));
			} else {
				target = "updateFail";
				setFLAG_UPDATE(true);
			}
		} catch (Exception e) {
			e.printStackTrace();
			HibernateSessionFactory.getSession().beginTransaction().rollback();
			// TODO: handle exception
		} finally {
			HibernateSessionFactory.getSession().close();
		}

		find(mapping, form, request, response);
		return mapping.findForward(target);
	}

	public ActionForward find(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception, ServletException {
		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;
		List data;

		MotivoBajaForm motivoBajaForm = (MotivoBajaForm) form;
		ActMotivoBajaDAO actMotivoBajaDAO = new ActMotivoBajaDAO();

		try {

			data = actMotivoBajaDAO.findAll();
			request.setAttribute("listaMotivoBaja", data);

			// TipoUnidadForm f = (TipoUnidadForm) listaTipoUnidad;
			// unidadForm.setActTipoUnidad(f);

			if (!isFLAG_UPDATE()) {
				motivoBajaForm.reset(mapping, request);
			} else {
				setFLAG_UPDATE(false);
			}

		} catch (Exception e) {
			e.printStackTrace();
			// TODO: handle exception
		} finally {
			HibernateSessionFactory.getSession().close();
		}
		return mapping.findForward(target);
	}

}