/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.saldei.web.action.activos;

import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessages;
import org.hibernate.exception.ConstraintViolationException;

import com.saldei.hibernate.tables.activos.ActSolicitudDAO;
import com.saldei.util.hibernate.dao.HibernateSessionFactory;
import com.saldei.web.form.activos.SolDescActForm;
import com.saldei.web.action.BaseAction;

/**
 * MyEclipse Struts Creation date: 05-28-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/unidadAction" name="unidadForm"
 *                input="/html/activos/unidad.jsp" parameter="accion"
 *                scope="request" validate="true"
 * @struts.action-forward name="back" path="/html/activos/unidad.jsp"
 * @struts.action-forward name="success" path="/html/activos/unidad.jsp"
 * @struts.action-forward name="fail" path="/html/activos/unidad.jsp"
 */
public class SolDescActAction extends BaseAction {

	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */

	@SuppressWarnings("deprecation")
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub
		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;

		SolDescActForm solDescActForm = (SolDescActForm) form;
		ActSolicitudDAO actSolicitudDAO = new ActSolicitudDAO();

		try {
			actSolicitudDAO.delete(solDescActForm.getActSolicitud());
			HibernateSessionFactory.getSession().beginTransaction().commit();
			errors.add("soldesca.mensaje.exito", new ActionError(
					"soldesca.mensaje.exito.delete"));

		} catch (ConstraintViolationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			errors.add("soldesca.mensajeError.error", new ActionError(
					"soldesca.mensajeError.error.nodelete"));
			HibernateSessionFactory.getSession().beginTransaction().rollback();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			HibernateSessionFactory.getSession().beginTransaction().rollback();
		} finally {
			HibernateSessionFactory.getSession().close();
		}

		find(mapping, form, request, response);
		return mapping.findForward(target);
	}

	@SuppressWarnings("deprecation")
	public ActionForward insert(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub

		SolDescActForm solDescActForm = (SolDescActForm) form;
		ActSolicitudDAO actSolicitudDAO = new ActSolicitudDAO();

		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;

		try {
			solDescActForm.validate(mapping, request, errors);
			if (errors.isEmpty()) {
				actSolicitudDAO.save(solDescActForm.getActSolicitud());
				HibernateSessionFactory.getSession().beginTransaction()
						.commit();
				errors.add("soldesca.mensaje.exito", new ActionError(
						"soldesca.mensaje.exito.insert"));
			} else {
				setFLAG_UPDATE(true);
			}
		} catch (Exception e) {
			e.printStackTrace();
			HibernateSessionFactory.getSession().beginTransaction().rollback();
			// TODO: handle exception
		} finally {
			HibernateSessionFactory.getSession().close();
		}

		find(mapping, form, request, response);
		return mapping.findForward(target);
	}

	public ActionForward update(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub
		SolDescActForm solDescActForm = (SolDescActForm) form;
		ActSolicitudDAO actSolicitudDAO = new ActSolicitudDAO();

		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;

		try {
			solDescActForm.validate(mapping, request, errors);
			if (errors.isEmpty()) {
				actSolicitudDAO.merge(solDescActForm.getActSolicitud());
				HibernateSessionFactory.getSession().beginTransaction()
						.commit();
				errors.add("soldesca.mensaje.exito", new ActionError(
						"soldesca.mensaje.exito.update"));
			} else {
				target = "updateFail";
				setFLAG_UPDATE(true);
			}
		}

		catch (Exception e) {
			e.printStackTrace();
			HibernateSessionFactory.getSession().beginTransaction().rollback();
			// TODO: handle exception
		} finally {
			HibernateSessionFactory.getSession().close();
		}

		find(mapping, form, request, response);
		return mapping.findForward(target);
	}

	public ActionForward find(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception, ServletException {
		String target = KEY_SUCCESS;
		HttpSession session = request.getSession(true);

		List data;

		SolDescActForm solDescActForm = (SolDescActForm) form;
		ActSolicitudDAO actSolicitudDAO = new ActSolicitudDAO();

		try {

			data = actSolicitudDAO.descActfindSolicitudes(session.getAttribute(
					"user").toString());
			request.setAttribute("listaSolicitudes", data);

			// TipoUnidadForm f = (TipoUnidadForm) listaTipoUnidad;
			// unidadForm.setActTipoUnidad(f);

			if (!isFLAG_UPDATE()) {
				solDescActForm.reset(mapping, request);
			} else {
				setFLAG_UPDATE(false);
			}

		} catch (Exception e) {
			e.printStackTrace();
			// TODO: handle exception
		} finally {
			HibernateSessionFactory.getSession().close();
		}
		return mapping.findForward(target);
	}

}