package com.saldei.hibernate.tables.inventario;

/**
 * AbstractInvDetMovActivoId generated by MyEclipse Persistence Tools
 */

public abstract class AbstractInvDetMovActivoId implements java.io.Serializable {

	// Fields

	private InvDetMovimiento invDetMovimiento;
	private Integer codActivo;

	// Constructors

	/** default constructor */
	public AbstractInvDetMovActivoId() {
	}

	/** full constructor */
	public AbstractInvDetMovActivoId(InvDetMovimiento invDetMovimiento,
			Integer codActivo) {
		this.invDetMovimiento = invDetMovimiento;
		this.codActivo = codActivo;
	}

	// Property accessors

	public InvDetMovimiento getInvDetMovimiento() {
		return this.invDetMovimiento;
	}

	public void setInvDetMovimiento(InvDetMovimiento invDetMovimiento) {
		this.invDetMovimiento = invDetMovimiento;
	}

	public Integer getCodActivo() {
		return this.codActivo;
	}

	public void setCodActivo(Integer codActivo) {
		this.codActivo = codActivo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AbstractInvDetMovActivoId))
			return false;
		AbstractInvDetMovActivoId castOther = (AbstractInvDetMovActivoId) other;

		return ((this.getInvDetMovimiento() == castOther.getInvDetMovimiento()) || (this
				.getInvDetMovimiento() != null
				&& castOther.getInvDetMovimiento() != null && this
				.getInvDetMovimiento().equals(castOther.getInvDetMovimiento())))
				&& ((this.getCodActivo() == castOther.getCodActivo()) || (this
						.getCodActivo() != null
						&& castOther.getCodActivo() != null && this
						.getCodActivo().equals(castOther.getCodActivo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getInvDetMovimiento() == null ? 0 : this
						.getInvDetMovimiento().hashCode());
		result = 37 * result
				+ (getCodActivo() == null ? 0 : this.getCodActivo().hashCode());
		return result;
	}

}