package com.saldei.hibernate.tables.inventario;

/**
 * AbstractInvDetMovActivo generated by MyEclipse Persistence Tools
 */

public abstract class AbstractInvDetMovActivo implements java.io.Serializable {

	// Fields

	private InvDetMovActivoId id;

	// Constructors

	/** default constructor */
	public AbstractInvDetMovActivo() {
	}

	/** full constructor */
	public AbstractInvDetMovActivo(InvDetMovActivoId id) {
		this.id = id;
	}

	// Property accessors

	public InvDetMovActivoId getId() {
		return this.id;
	}

	public void setId(InvDetMovActivoId id) {
		this.id = id;
	}

}