package com.saldei.hibernate.tables.inventario;

/**
 * AbstractInvMovimientoId generated by MyEclipse Persistence Tools
 */

public abstract class AbstractInvMovimientoId implements java.io.Serializable {

	// Fields

	private Integer anio;
	private Integer correlativoMov;

	// Constructors

	/** default constructor */
	public AbstractInvMovimientoId() {
	}

	/** full constructor */
	public AbstractInvMovimientoId(Integer anio, Integer correlativoMov) {
		this.anio = anio;
		this.correlativoMov = correlativoMov;
	}

	// Property accessors

	public Integer getAnio() {
		return this.anio;
	}

	public void setAnio(Integer anio) {
		this.anio = anio;
	}

	public Integer getCorrelativoMov() {
		return this.correlativoMov;
	}

	public void setCorrelativoMov(Integer correlativoMov) {
		this.correlativoMov = correlativoMov;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AbstractInvMovimientoId))
			return false;
		AbstractInvMovimientoId castOther = (AbstractInvMovimientoId) other;

		return ((this.getAnio() == castOther.getAnio()) || (this.getAnio() != null
				&& castOther.getAnio() != null && this.getAnio().equals(
				castOther.getAnio())))
				&& ((this.getCorrelativoMov() == castOther.getCorrelativoMov()) || (this
						.getCorrelativoMov() != null
						&& castOther.getCorrelativoMov() != null && this
						.getCorrelativoMov().equals(
								castOther.getCorrelativoMov())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAnio() == null ? 0 : this.getAnio().hashCode());
		result = 37
				* result
				+ (getCorrelativoMov() == null ? 0 : this.getCorrelativoMov()
						.hashCode());
		return result;
	}

}