package com.saldei.hibernate.tables.inventario;

// Generated by MyEclipse Persistence Tools

/**
 * CtlCorrelativo generated by MyEclipse Persistence Tools
 */
public class CtlCorrelativo extends AbstractCtlCorrelativo implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public CtlCorrelativo() {
	}

	/** minimal constructor */
	public CtlCorrelativo(String clave) {
		super(clave);
	}

	/** full constructor */
	public CtlCorrelativo(String clave, Integer anio, long correlativo) {
		super(clave, anio, correlativo);
	}

}
