package com.saldei.hibernate.tables.inventario;

// Generated by MyEclipse Persistence Tools

/**
 * InvBodegaRecursosId generated by MyEclipse Persistence Tools
 */
public class InvBodegaRecursosId extends AbstractInvBodegaRecursosId implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public InvBodegaRecursosId() {
	}

	/** full constructor */
	public InvBodegaRecursosId(InvRecurso invRecurso, String codBodega) {
		super(invRecurso, codBodega);
	}

}
