package com.saldei.hibernate.tables.inventario;

// Generated by MyEclipse Persistence Tools

/**
 * InvDetMovActivo generated by MyEclipse Persistence Tools
 */
public class InvDetMovActivo extends AbstractInvDetMovActivo implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public InvDetMovActivo() {
	}

	/** full constructor */
	public InvDetMovActivo(InvDetMovActivoId id) {
		super(id);
	}

}
