package com.saldei.hibernate.tables.inventario;

// Generated by MyEclipse Persistence Tools

import java.util.Date;
import java.util.Set;

/**
 * InvSubCategoria generated by MyEclipse Persistence Tools
 */
public class InvSubCategoria extends AbstractInvSubCategoria implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public InvSubCategoria() {
	}

	/** minimal constructor */
	public InvSubCategoria(InvSubCategoriaId id) {
		super.setId(id);
	}

	/**
	 * @param id
	 * @param nombre
	 * @param fechaCreacion
	 * @param invRecursos
	 */
	public InvSubCategoria(InvSubCategoriaId id, String nombre,
			Date fechaCreacion, Set invRecursos) {
		super(id, nombre, fechaCreacion, invRecursos);
		// TODO Auto-generated constructor stub
	}

	/**
	 * @param id
	 * @param nombre
	 */
	public InvSubCategoria(InvSubCategoriaId id, String nombre) {
		super(id, nombre);
		// TODO Auto-generated constructor stub
	}

	
}
