package com.saldei.hibernate.tables.inventario;

// Generated by MyEclipse Persistence Tools

/**
 * InvSubCategoriaId generated by MyEclipse Persistence Tools
 */
public class InvSubCategoriaId extends AbstractInvSubCategoriaId implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public InvSubCategoriaId() {
	}

	/** full constructor */
	public InvSubCategoriaId(InvCategoria invCategoria, String codSubCategoria) {
		super(invCategoria, codSubCategoria);
	}

}
