package com.saldei.hibernate.tables.inventario;

// Generated by MyEclipse Persistence Tools

import java.util.Date;
import java.util.Set;

/**
 * InvTipoMov generated by MyEclipse Persistence Tools
 */
public class InvTipoMov extends AbstractInvTipoMov implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public InvTipoMov() {
	}

	/** minimal constructor */
	public InvTipoMov(Integer codTipoMov) {
		super(codTipoMov);
	}

	/**
	 * @param codTipoMov
	 * @param descripcion
	 * @param operacion
	 * @param fechaCreacion
	 * @param invMovimientos
	 */
	public InvTipoMov(Integer codTipoMov, String descripcion, String operacion,
			Date fechaCreacion, Set invMovimientos) {
		super(codTipoMov, descripcion, operacion, fechaCreacion, invMovimientos);
		// TODO Auto-generated constructor stub
	}

	

}
