package com.saldei.hibernate.tables.inventario;

/**
 * AbstractInvBodegaRecursosId generated by MyEclipse Persistence Tools
 */

public abstract class AbstractInvBodegaRecursosId implements
		java.io.Serializable {

	// Fields

	private InvRecurso invRecurso;
	private String codBodega;

	// Constructors

	/** default constructor */
	public AbstractInvBodegaRecursosId() {
	}

	/** full constructor */
	public AbstractInvBodegaRecursosId(InvRecurso invRecurso, String codBodega) {
		this.invRecurso = invRecurso;
		this.codBodega = codBodega;
	}

	// Property accessors

	public InvRecurso getInvRecurso() {
		return this.invRecurso;
	}

	public void setInvRecurso(InvRecurso invRecurso) {
		this.invRecurso = invRecurso;
	}

	public String getCodBodega() {
		return this.codBodega;
	}

	public void setCodBodega(String codBodega) {
		this.codBodega = codBodega;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AbstractInvBodegaRecursosId))
			return false;
		AbstractInvBodegaRecursosId castOther = (AbstractInvBodegaRecursosId) other;

		return ((this.getInvRecurso() == castOther.getInvRecurso()) || (this
				.getInvRecurso() != null
				&& castOther.getInvRecurso() != null && this.getInvRecurso()
				.equals(castOther.getInvRecurso())))
				&& ((this.getCodBodega() == castOther.getCodBodega()) || (this
						.getCodBodega() != null
						&& castOther.getCodBodega() != null && this
						.getCodBodega().equals(castOther.getCodBodega())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getInvRecurso() == null ? 0 : this.getInvRecurso()
						.hashCode());
		result = 37 * result
				+ (getCodBodega() == null ? 0 : this.getCodBodega().hashCode());
		return result;
	}

}