package com.saldei.hibernate.tables.inventario;

// Generated by MyEclipse Persistence Tools

import java.util.Set;

/**
 * InvBodega generated by MyEclipse Persistence Tools
 */
public class InvBodega extends AbstractInvBodega implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public InvBodega() {
	}

	/**
	 * @param codBodega
	 * @param nombre
	 * @param ubicacion
	 * @param estado
	 * @param invMovimientos
	 * @param invExistencias
	 */
	public InvBodega(Integer codBodega, String nombre, String ubicacion,
			String estado, Set invMovimientos, Set invExistencias) {
		super(codBodega, nombre, ubicacion, estado, invMovimientos,
				invExistencias);
		// TODO Auto-generated constructor stub
	}

	/**
	 * @param codBodega
	 * @param nombre
	 * @param estado
	 */
	public InvBodega(Integer codBodega, String nombre, String estado) {
		super(codBodega, nombre, estado);
		// TODO Auto-generated constructor stub
	}

	public InvBodega(Integer codBodega) {
		this.setCodBodega(codBodega);
		// TODO Auto-generated constructor stub
	}

}
