package com.saldei.hibernate.tables.inventario;

// Generated by MyEclipse Persistence Tools

import java.util.Date;
import java.util.Set;

/**
 * InvCategoria generated by MyEclipse Persistence Tools
 */
public class InvCategoria extends AbstractInvCategoria implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public InvCategoria() {
	}

	

	/**
	 * @param codCategoria
	 * @param nombre
	 * @param fechaCreacion
	 * @param invSubCategorias
	 */
	public InvCategoria(String codCategoria, String nombre, Date fechaCreacion,
			Set invSubCategorias) {
		super(codCategoria, nombre, fechaCreacion, invSubCategorias);
		// TODO Auto-generated constructor stub
	}



	/**
	 * @param codCategoria
	 * @param nombre
	 */
	public InvCategoria(String codCategoria, String nombre) {
		super(codCategoria, nombre);
		// TODO Auto-generated constructor stub
	}

}
