package com.saldei.hibernate.tables.inventario;

// Generated by MyEclipse Persistence Tools

/**
 * InvExistenciaId generated by MyEclipse Persistence Tools
 */
public class InvExistenciaId extends AbstractInvExistenciaId implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public InvExistenciaId() {
	}

	/** full constructor */
	public InvExistenciaId(InvBodega invBodega, InvRecurso invRecurso) {
		super(invBodega, invRecurso);
	}

}
