package com.saldei.hibernate.tables.inventario;

import java.util.Date;

// Generated by MyEclipse Persistence Tools

/**
 * InvExistencia generated by MyEclipse Persistence Tools
 */
public class InvExistencia extends AbstractInvExistencia implements
		java.io.Serializable {
	
	// Constructors

	/**
	 * @return the fechaCreacion
	 */
	

	/** default constructor */
	public InvExistencia() {
	}

	/** minimal constructor */
	public InvExistencia(InvExistenciaId id) {
		super(id);
	}

	/**
	 * @param id
	 * @param existencia
	 * @param minimo
	 */
	public InvExistencia(InvExistenciaId id, double existencia, Integer minimo) {
		super(id, existencia, minimo);
		// TODO Auto-generated constructor stub
	}

}
