/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.saldei.web.form.activos;

import java.util.ResourceBundle;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.saldei.hibernate.tables.activos.ActActivo;
import com.saldei.hibernate.tables.activos.ActMotivoBaja;
import com.saldei.hibernate.tables.activos.ActTipoUnidad;
import com.saldei.hibernate.tables.activos.ActUnidad;

/** 
 * MyEclipse Struts
 * Creation date: 07-03-2009
 * 
 * XDoclet definition:
 * @struts.form name="bajaActivoForm"
 */
public class BajaActivoForm extends ActionForm {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	/*
	 * Generated Methods
	 */
	private String recursoDesc;
	private String estadoDescr;
	private String codResponsable2;
	private String responsable2;
	private String codUnidad2;
	//private String codUnidad;
	private String descripcion2;
	private String descripcion;
	private String responsable;
	private Integer codBaja;
	private String motivoBajaDesc;
	private Integer numSerie;
	private String codAltUca;
	private String codActivo;
	
	
	
		/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ActActivo actActivo = new ActActivo(new ActUnidad(new ActTipoUnidad()),new ActMotivoBaja()) ;

	
	public void validate(ActionMapping mapping,
			HttpServletRequest request, ActionErrors errors) {
		// TODO Auto-generated method stub
		String accion = request.getParameter("accion");
		accion = (accion==null)?"":accion;
		
		ResourceBundle mensajes = ResourceBundle.getBundle("com.saldei.web.ApplicationResources");
		if(!accion.equals(mensajes.getString("opc.cancel")) && !accion.equals(mensajes.getString("opc.find"))){
			if(this.getCodActivo()==null || this.getCodActivo().trim().equals("")){
				errors.add("bajaActivo.mensajeError.error", new ActionError("bajaActivo.mensajeError.error.insert"));
				}
			}
			if(this.getCodBaja()== null || this.getCodBaja()==0){
				errors.add("bajaActivo.motivoBaja.requerido", new ActionError("bajaActivo.motivoBaja.requerido"));
			}
		
		}				
		
	

	
	
	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#getActUnidad()
	 */
	public ActUnidad getActUnidad() {
		return actActivo.getActUnidad();
	}
	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#getCodActivo()
	 */
	public String getCodActivo() {
		if(actActivo.getCodActivo()==null)
			return "";
			else
				return String.valueOf(actActivo.getCodActivo());
	}
	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#getCodAltUca()
	 */
	public String getCodAltUca() {
		return actActivo.getCodAltUca();
	}
	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#getCodRecurso()
	 */
	public String getCodRecurso() {
		return actActivo.getCodRecurso();
	}
	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#getEstado()
	 */
	public String getEstado() {
		return actActivo.getEstado();
	}
	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#getMotivo()
	 */
	public String getMotivo() {
		return actActivo.getMotivo();
	}
	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#getNumSerie()
	 */
	public String getNumSerie() {
		return actActivo.getNumSerie();
	}
	/**
	 * @param codActivo
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#setCodActivo(java.lang.Integer)
	 */
	public void setNumSerie(String numSerie) {
		actActivo.setNumSerie(numSerie);
	}

	public void setCodActivo(String codActivo) {
		if(codActivo==null || codActivo.trim().equals(""))
			actActivo.setCodActivo(0);
		else
			actActivo.setCodActivo(Integer.valueOf(codActivo));
	}
	/**
	 * @param codAltUca
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#setCodAltUca(java.lang.String)
	 */
	public void setCodAltUca(String codAltUca) {
		actActivo.setCodAltUca(codAltUca);
	}
	/**
	 * @param codRecurso
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#setCodRecurso(java.lang.String)
	 */
	public void setCodRecurso(String codRecurso) {
		actActivo.setCodRecurso(codRecurso);
	}
	/**
	 * @param estado
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#setEstado(java.lang.String)
	 */
	public void setEstado(String estado) {
		actActivo.setEstado(estado);
	}
	/**
	 * @param motivo
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#setMotivo(java.lang.String)
	 */
	public void setMotivo(String motivo) {
		actActivo.setMotivo(motivo);
	}
	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActUnidad#getCodUnidad()
	 */
	public Integer getCodUnidad() {
			return this.actActivo.getActUnidad().getCodUnidad();		
	}
	
	public void setCodUnidad(Integer codUnidad) {
			this.actActivo.getActUnidad().setCodUnidad(codUnidad);
	}
	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		this.actActivo = new ActActivo(new ActUnidad(new ActTipoUnidad()),new ActMotivoBaja()) ;
		//this.recursoDesc = null;
		//this.setCodActivo(null);
		this.setRecursoDesc("");
		this.setCodAltUca("");
		this.setNumSerie("");
		
		this.setCodAltUca("");
		this.setCodRecurso("");
		this.setMotivoBajaDesc("");
		this.setCodBaja(0);
		this.setCodUnidad2("");
		this.setDescripcion("");
		this.setDescripcion2("");
		this.setRecursoDesc("");
		this.setResponsable("");
		this.setResponsable2("");
		this.setMotivoBajaDesc("");
		
	}
	/**
	 * @return the recursoDesc
	 */
	public String getRecursoDesc() {
		return recursoDesc;
	}
	/**
	 * @param recursoDesc the recursoDesc to set
	 */
	public void setRecursoDesc(String recursoDesc) {
		this.recursoDesc = recursoDesc;
	}
	/**
	 * @return the estadoDescr
	 */
	public String getEstadoDescr() {
		return estadoDescr;
	}
	/**
	 * @param estadoDescr the estadoDescr to set
	 */
	public void setEstadoDescr(String estadoDescr) {
		this.estadoDescr = estadoDescr;
	}
	/**
	 * @return the codResponsable2
	 */
	public String getCodResponsable2() {
		return codResponsable2;
	}
	/**
	 * @param codResponsable2 the codResponsable2 to set
	 */
	public void setCodResponsable2(String codResponsable2) {
		this.codResponsable2 = codResponsable2;
	}
	/**
	 * @return the responsable2
	 */
	public String getResponsable2() {
		return responsable2;
	}
	/**
	 * @param responsable2 the responsable2 to set
	 */
	public void setResponsable2(String responsable2) {
		this.responsable2 = responsable2;
	}
	/**
	 * @return the codUnidad2
	 */
	public String getCodUnidad2() {
		return codUnidad2;
	}
	/**
	 * @param codUnidad2 the codUnidad2 to set
	 */
	public void setCodUnidad2(String codUnidad2) {
		this.codUnidad2 = codUnidad2;
	}
	/**
	 * @return the descripcion2
	 */
	public String getDescripcion2() {
		return descripcion2;
	}
	/**
	 * @param descripcion2 the descripcion2 to set
	 */
	public void setDescripcion2(String descripcion2) {
		this.descripcion2 = descripcion2;
	}
	/**
	 * @return the actActivo
	 */
	public ActActivo getActActivo() {
		return actActivo;
	}
	/**
	 * @param actActivo the actActivo to set
	 */
	public void setActActivo(ActActivo actActivo) {
		this.actActivo = actActivo;
	}
	/**
	 * @return the descripcion
	 */
	public String getDescripcion() {
		return descripcion;
	}
	/**
	 * @param descripcion the descripcion to set
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	/**
	 * @return the responsable
	 */
	public String getResponsable() {
		return responsable;
	}
	/**
	 * @param responsable the responsable to set
	 */
	public void setResponsable(String responsable) {
		this.responsable = responsable;
	}



	public Integer getCodBaja() {
		return actActivo.getActMotivoBaja().getCodBaja();
	}



	public void setCodBaja(Integer codBaja) {
		this.actActivo.getActMotivoBaja().setCodBaja(codBaja);
	}



	public String getMotivoBajaDesc() {
		return motivoBajaDesc;
	}



	public void setMotivoBajaDesc(String motivoBajaDesc) {
		this.motivoBajaDesc = motivoBajaDesc;
	}

}