/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.saldei.web.form.activos;

import java.io.File;
import java.util.ResourceBundle;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import com.saldei.hibernate.tables.activos.ActCotizacion;
import com.saldei.hibernate.tables.activos.ActCotizacionId;
import com.saldei.hibernate.tables.activos.ActProveedor;
import com.saldei.hibernate.tables.activos.ActSolicitud;
import com.saldei.hibernate.tables.activos.ActSolicitudId;

/** 
 * MyEclipse Struts
 * Creation date: 07-01-2009
 * 
 * XDoclet definition:
 * @struts.form name="cotizacionForm"
 */
public class CotizacionForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** actCotizacion property */
	private ActCotizacion actCotizacion = new ActCotizacion(new ActCotizacionId(new ActSolicitud(new ActSolicitudId()),null),new ActProveedor());		
	private String flagDetalleCotizacion;
    private FormFile archivoPDF;
	
	/*
	 * Generated Methods
	 */
	

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActCotizacion#getComentario()
	 */
	public String getComentario() {
		return actCotizacion.getComentario();
	}

	/**
	 * @param comentario
	 * @see com.saldei.hibernate.tables.activos.AbstractActCotizacion#setComentario(java.lang.String)
	 */
	public void setComentario(String comentario) {
		actCotizacion.setComentario(comentario);
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActProveedor#getCodProveedor()
	 */
	public String getCodProveedor() {
		return this.actCotizacion.getActProveedor().getCodProveedor();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActProveedor#getNombre()
	 */
	public String getNombreProveedor() {
		return this.actCotizacion.getActProveedor().getNombre();
	}

	/**
	 * @param codProveedor
	 * @see com.saldei.hibernate.tables.activos.AbstractActProveedor#setCodProveedor(java.lang.String)
	 */
	public void setCodProveedor(String codProveedor) {
		this.actCotizacion.getActProveedor().setCodProveedor(codProveedor);
	}

	/**
	 * @param nombre
	 * @see com.saldei.hibernate.tables.activos.AbstractActProveedor#setNombre(java.lang.String)
	 */
	public void setNombreProveedor(String nombreProveedor) {
		this.actCotizacion.getActProveedor().setNombre(nombreProveedor);
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public void validate(ActionMapping mapping,
			HttpServletRequest request,ActionErrors errors) {
		// TODO Auto-generated method stub
		String accion = request.getParameter("accion");
		accion = (accion==null)?"":accion;
		
		ResourceBundle mensajes = ResourceBundle.getBundle("com.saldei.web.ApplicationResources");
	
		if(!accion.equals(mensajes.getString("opc.cancel")) && !accion.equals(mensajes.getString("opc.find"))){
			if(this.getNombreProveedor() == null || this.getCodProveedor().trim().equals("")){
				errors.add("cotizacion.proveedor.requerido", new ActionError("cotizacion.proveedor.requerido"));
			}
			
			if(this.getComentario() == null || this.getComentario().trim().equals("")){
				errors.add("suministro.descripcion.requerido", new ActionError("suministro.descripcion.requerido"));
			}
			
		}
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		this.actCotizacion = new ActCotizacion(new ActCotizacionId(new ActSolicitud(new ActSolicitudId()),null),new ActProveedor());
	}

	/** 
	 * Returns the actCotizacion.
	 * @return ActCotizacion
	 */
	public ActCotizacion getActCotizacion() {
		return actCotizacion;
	}

	/** 
	 * Set the actCotizacion.
	 * @param actCotizacion The actCotizacion to set
	 */
	public void setActCotizacion(ActCotizacion actCotizacion) {
		this.actCotizacion = actCotizacion;
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActCotizacion#getActProveedor()
	 */
	public ActProveedor getActProveedor() {
		return actCotizacion.getActProveedor();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActCotizacion#getId()
	 */
	public ActCotizacionId getId() {
		return actCotizacion.getId();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActCotizacion#getUrlCotizacion()
	 */
	public String getUrlCotizacion() {
		return actCotizacion.getUrlCotizacion();
	}

	/**
	 * @param actProveedor
	 * @see com.saldei.hibernate.tables.activos.AbstractActCotizacion#setActProveedor(com.saldei.hibernate.tables.activos.ActProveedor)
	 */
	public void setActProveedor(ActProveedor actProveedor) {
		actCotizacion.setActProveedor(actProveedor);
	}

	/**
	 * @param id
	 * @see com.saldei.hibernate.tables.activos.AbstractActCotizacion#setId(com.saldei.hibernate.tables.activos.ActCotizacionId)
	 */
	public void setId(ActCotizacionId id) {
		actCotizacion.setId(id);
	}

	/**
	 * @param urlCotizacion
	 * @see com.saldei.hibernate.tables.activos.AbstractActCotizacion#setUrlCotizacion(java.lang.String)
	 */
	public void setUrlCotizacion(String urlCotizacion) {
		actCotizacion.setUrlCotizacion(urlCotizacion);
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitudId#getCodSolicitud()
	 */
	public String getCodSolicitud() {
		if(this.actCotizacion.getId().getActSolicitud().getId().getCodSolicitud() != null)
			return String.valueOf(this.actCotizacion.getId().getActSolicitud().getId().getCodSolicitud());
		else return "";
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitudId#getTipoSolicitud()
	 */
	public String getTipoSolicitud() {
		return this.actCotizacion.getId().getActSolicitud().getId().getTipoSolicitud();
	}

	/**
	 * @param codSolicitud
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitudId#setCodSolicitud(java.lang.Integer)
	 */
	public void setCodSolicitud(String codSolicitud) {
		if (codSolicitud != null && !codSolicitud.trim().equals(""))
			this.actCotizacion.getId().getActSolicitud().getId().setCodSolicitud(Integer.valueOf(codSolicitud));
		
	}

	/**
	 * @param tipoSolicitud
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitudId#setTipoSolicitud(java.lang.String)
	 */
	public void setTipoSolicitud(String tipoSolicitud) {
		this.actCotizacion.getId().getActSolicitud().getId().setTipoSolicitud(tipoSolicitud);
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActCotizacionId#getCodCotizacion()
	 */
	public String getCodCotizacion() {
		if(this.actCotizacion.getId().getCodCotizacion() != null)
			return String.valueOf(this.actCotizacion.getId().getCodCotizacion());
		else 
			return "";
	}

	/**
	 * @param codCotizacion
	 * @see com.saldei.hibernate.tables.activos.AbstractActCotizacionId#setCodCotizacion(java.lang.Integer)
	 */
	public void setCodCotizacion(String codCotizacion) {
		if(codCotizacion != null && !codCotizacion.trim().equals(""))
			this.actCotizacion.getId().setCodCotizacion(Integer.valueOf(codCotizacion));
	}

	/**
	 * @return the flagDetalleCotizacion
	 */
	public String getFlagDetalleCotizacion() {
		return flagDetalleCotizacion;
	}

	/**
	 * @param flagDetalleCotizacion the flagDetalleCotizacion to set
	 */
	public void setFlagDetalleCotizacion(String flagDetalleCotizacion) {
		this.flagDetalleCotizacion = flagDetalleCotizacion;
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#getEstado()
	 */
	public String getEstado() {
		return this.actCotizacion.getId().getActSolicitud().getEstado();
	}

	/**
	 * @param estado
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#setEstado(java.lang.String)
	 */
	public void setEstado(String estado) {
		this.actCotizacion.getId().getActSolicitud().setEstado(estado);
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.ActSolicitud#getEstadoDesc()
	 */
	public String getEstadoDesc() {
		return this.actCotizacion.getId().getActSolicitud().getEstadoDesc();
	}
	
	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#getCodBodega()
	 */
	public Integer getCodBodega() {
		return actCotizacion.getId().getActSolicitud().getCodBodega();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.ActSolicitud#getDesBodega()
	 */
	public String getDesBodega() {
		return actCotizacion.getId().getActSolicitud().getDesBodega();
	}

	/**
	 * @param codBodega
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#setCodBodega(java.lang.Integer)
	 */
	public void setCodBodega(Integer codBodega) {
		actCotizacion.getId().getActSolicitud().setCodBodega(codBodega);
	}

	/**
	 * @return the archivoPDF
	 */
	public FormFile getArchivoPDF() {
		return archivoPDF;
	}

	/**
	 * @param archivoPDF the archivoPDF to set
	 */
	public void setArchivoPDF(FormFile archivoPDF) {
		this.archivoPDF = archivoPDF;
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActCotizacion#getIva()
	 */
	public String getIva() {
		return actCotizacion.getIva();
	}

	/**
	 * @param iva
	 * @see com.saldei.hibernate.tables.activos.AbstractActCotizacion#setIva(java.lang.String)
	 */
	public void setIva(String iva) {
		actCotizacion.setIva(iva);
	}
	
}