/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.saldei.web.form.activos;

import java.text.ParseException;
import java.text.SimpleDateFormat;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.saldei.hibernate.tables.activos.ActActivo;
import com.saldei.hibernate.tables.activos.ActDetSolicitud;
import com.saldei.hibernate.tables.activos.ActDetSolicitudId;
import com.saldei.hibernate.tables.activos.ActSolicitud;
import com.saldei.hibernate.tables.activos.ActSolicitudId;

/** 
 * MyEclipse Struts
 * Creation date: 06-23-2009
 * 
 * XDoclet definition:
 * @struts.form name="detAprSolPrestamoForm"
 */
public class DetAprSolPrestamoForm extends ActionForm {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ActDetSolicitud actDetSolicitud = new ActDetSolicitud(new ActDetSolicitudId(new ActSolicitud(new ActSolicitudId("",0))), new ActActivo());
	//ActSolicitud actSolicitud = new ActSolicitud(new ActSolicitudId());
	private String responsable;
	private String solicitante;
	SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
	private String fecha_ini;
	private String fecha_fin;
	private String nombreRecurso;
	private String codSolicitante;
	private String estado;
	private String comentario;
	private String codPropietario;
	private String ubicacion;
	private String categoria;
	private String subcat;
	private String serie;
	private String propietario;
	private int codUnidad;
	private String estadoNombre;
	private String motivoRechazo;

	/*
	 * Generated Methods
	 */

	/**
	 * @return the motivoRechazo
	 */
	public String getMotivoRechazo() {
		return motivoRechazo;
	}


	/**
	 * @param motivoRechazo the motivoRechazo to set
	 */
	public void setMotivoRechazo(String motivoRechazo) {
		this.motivoRechazo = motivoRechazo;
	}


	/**
	 * @return the estadoNombre
	 */
	public String getEstadoNombre() {
		return estadoNombre;
	}


	/**
	 * @param estadoNombre the estadoNombre to set
	 */
	public void setEstadoNombre(String estadoNombre) {
		this.estadoNombre = estadoNombre;
	}


	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		ActSolicitud actSolicitud = this.actDetSolicitud.getId().getActSolicitud();
		this.actDetSolicitud = new ActDetSolicitud(new ActDetSolicitudId(new ActSolicitud(new ActSolicitudId("",0))), new ActActivo());
		this.actDetSolicitud.getId().setActSolicitud(actSolicitud);
		this.setCategoria("");
		this.setNombreRecurso("");
		this.setSubcat("");
		this.setUbicacion("");
		this.setSerie("");
	}


	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActDetSolicitud#getActActivo()
	 */
	public ActActivo getActActivo() {
		return this.actDetSolicitud.getActActivo();
	}
	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActDetSolicitud#getCantidad()
	 */
	public Integer getCantidad() {
		return this.actDetSolicitud.getCantidad();
	}
	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActDetSolicitud#getCodRecurso()
	 */
	public String getCodRecurso() {
		return this.actDetSolicitud.getCodRecurso();
	}
	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActDetSolicitud#getId()
	 */
	public ActDetSolicitudId getId() {
		return this.actDetSolicitud.getId();
	}
	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActDetSolicitud#getPrecioUnitario()
	 */
	public double getPrecioUnitario() {
		return this.actDetSolicitud.getPrecioUnitario();
	}
	/**
	 * @param actActivo
	 * @see com.saldei.hibernate.tables.activos.AbstractActDetSolicitud#setActActivo(com.saldei.hibernate.tables.activos.ActActivo)
	 */
	public void setActActivo(ActActivo actActivo) {
		this.actDetSolicitud.setActActivo(actActivo);
	}
	/**
	 * @param cantidad
	 * @see com.saldei.hibernate.tables.activos.AbstractActDetSolicitud#setCantidad(java.lang.Integer)
	 */
	public void setCantidad(Integer cantidad) {
		this.actDetSolicitud.setCantidad(cantidad);
	}
	/**
	 * @param codRecurso
	 * @see com.saldei.hibernate.tables.activos.AbstractActDetSolicitud#setCodRecurso(java.lang.String)
	 */
	public void setCodRecurso(String codRecurso) {
		this.actDetSolicitud.setCodRecurso(codRecurso);
	}
	/**
	 * @param id
	 * @see com.saldei.hibernate.tables.activos.AbstractActDetSolicitud#setId(com.saldei.hibernate.tables.activos.ActDetSolicitudId)
	 */
	public void setId(ActDetSolicitudId id) {
		this.actDetSolicitud.setId(id);
	}
	/**
	 * @param precioUnitario
	 * @see com.saldei.hibernate.tables.activos.AbstractActDetSolicitud#setPrecioUnitario(double)
	 */
	public void setPrecioUnitario(double precioUnitario) {
		this.actDetSolicitud.setPrecioUnitario(precioUnitario);
	}
	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#getCodActivo()
	 */
	public Integer getCodActivo() {
		return this.actDetSolicitud.getActActivo().getCodActivo();
	}
	/**
	 * @param codActivo
	 * @see com.saldei.hibernate.tables.activos.AbstractActActivo#setCodActivo(java.lang.Integer)
	 */
	public void setCodActivo(Integer codActivo) {
		this.actDetSolicitud.getActActivo().setCodActivo(codActivo);
	}
	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActDetSolicitudId#getActSolicitud()
	 */
	public ActSolicitud getActSolicitud() {
		return this.actDetSolicitud.getId().getActSolicitud();
	}
	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActDetSolicitudId#getCorrelativo()
	 */
	public Integer getCorrelativo() {
		return this.actDetSolicitud.getId().getCorrelativo();
	}
	/**
	 * @param actSolicitud
	 * @see com.saldei.hibernate.tables.activos.AbstractActDetSolicitudId#setActSolicitud(com.saldei.hibernate.tables.activos.ActSolicitud)
	 */
	public void setActSolicitud(ActSolicitud actSolicitud) {
		this.actDetSolicitud.getId().setActSolicitud(actSolicitud);
	}
	/**
	 * @param correlativo
	 * @see com.saldei.hibernate.tables.activos.AbstractActDetSolicitudId#setCorrelativo(java.lang.Integer)
	 */
	public void setCorrelativo(Integer correlativo) {
		this.actDetSolicitud.getId().setCorrelativo(correlativo);
	}
	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitudId#getCodSolicitud()
	 */
	public Integer getCodSolicitud() {
		return this.actDetSolicitud.getId().getActSolicitud().getId().getCodSolicitud();
	}
	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitudId#getTipoSolicitud()
	 */
	public String getTipoSolicitud() {
		return this.actDetSolicitud.getId().getActSolicitud().getId().getTipoSolicitud();
	}
	/**
	 * @param codSolicitud
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitudId#setCodSolicitud(java.lang.Integer)
	 */
	public void setCodSolicitud(Integer codSolicitud) {
		this.actDetSolicitud.getId().getActSolicitud().getId().setCodSolicitud(codSolicitud);
	}
	/**
	 * @param tipoSolicitud
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitudId#setTipoSolicitud(java.lang.String)
	 */
	public void setTipoSolicitud(String tipoSolicitud) {
		actDetSolicitud.getId().getActSolicitud().getId().setTipoSolicitud(tipoSolicitud);
		
	}

	/**
	 * @return the actDetSolicitud
	 */
	public ActDetSolicitud getActDetSolicitud() {
		return actDetSolicitud;
	}

	/**
	 * @param actDetSolicitud the actDetSolicitud to set
	 */
	public void setActDetSolicitud(ActDetSolicitud actDetSolicitud) {
		this.actDetSolicitud = actDetSolicitud;
	}

	/**
	 * @return the responsable
	 */
	public String getResponsable() {
		return responsable;
	}

	/**
	 * @param responsable the responsable to set
	 */
	public void setResponsable(String responsable) {
		this.responsable = responsable;
	}
	
	/**
	 * @return the fecha_ini
	 */
	public String getFecha_ini() {
		String fecha = "";
		if(this.actDetSolicitud.getId().getActSolicitud().getFechaIniPrestamo() != null)
			fecha = sdf.format(this.actDetSolicitud.getId().getActSolicitud().getFechaIniPrestamo());
		return fecha;
	}

	/**
	 * @param fecha_ini the fecha_ini to set
	 */
	public void setFecha_ini(String fecha_ini) {
		this.fecha_ini = fecha_ini;
		try {
			this.actDetSolicitud.getId().getActSolicitud().setFechaIniPrestamo(sdf.parse(fecha_ini));
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	/**
	 * @return the fecha_fin
	 */
	public String getFecha_fin() {
		String fecha = "";
		if(this.actDetSolicitud.getId().getActSolicitud().getFechaFinPrestamo() != null)
			fecha = sdf.format(this.actDetSolicitud.getId().getActSolicitud().getFechaFinPrestamo());
		return fecha; 
	}

	/**
	 * @param fecha_fin the fecha_fin to set
	 */
	public void setFecha_fin(String fecha_fin) {
		this.fecha_fin = fecha_fin;
		try {
			this.actDetSolicitud.getId().getActSolicitud().setFechaFinPrestamo((sdf.parse(fecha_fin)));
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/**
	 * @return the nombreRecurso
	 */
	public String getNombreRecurso() {
		return nombreRecurso;
	}

	/**
	 * @param nombreRecurso the nombreRecurso to set
	 */
	public void setNombreRecurso(String nombreRecurso) {
		this.nombreRecurso = nombreRecurso;
	}

	/**
	 * @return the codSolicitante
	 */
	public String getCodSolicitante() {
		return codSolicitante;
	}

	/**
	 * @param codSolicitante the codSolicitante to set
	 */
	public void setCodSolicitante(String codSolicitante) {
		this.codSolicitante = codSolicitante;
	}

	/**
	 * @return the estado
	 */
	public String getEstado() {
		return estado;
	}

	/**
	 * @param estado the estado to set
	 */
	public void setEstado(String estado) {
		this.estado = estado;
	}

	/**
	 * @return the comentario
	 */
	public String getComentario() {
		return comentario;
	}

	/**
	 * @param comentario the comentario to set
	 */
	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	/**
	 * @return the propietario
	 */
	public String getCodPropietario() {
		return codPropietario;
	}

	/**
	 * @param propietario the propietario to set
	 */
	public void setcodPropietario(String codPropietario) {
		this.codPropietario = codPropietario;
	}

	/**
	 * @return the codUnidad
	 */
	public int getCodUnidad() {
		return codUnidad;
	}

	/**
	 * @param codUnidad the codUnidad to set
	 */
	public void setCodUnidad(int codUnidad) {
		this.codUnidad = codUnidad;
	}


	/**
	 * @return the ubicacion
	 */
	public String getUbicacion() {
		return ubicacion;
	}


	/**
	 * @param ubicacion the ubicacion to set
	 */
	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}


	/**
	 * @return the categoria
	 */
	public String getCategoria() {
		return categoria;
	}


	/**
	 * @param categoria the categoria to set
	 */
	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}


	/**
	 * @return the subcat
	 */
	public String getSubcat() {
		return subcat;
	}


	/**
	 * @param subcat the subcat to set
	 */
	public void setSubcat(String subcat) {
		this.subcat = subcat;
	}


	/**
	 * @return the serie
	 */
	public String getSerie() {
		return serie;
	}


	/**
	 * @param serie the serie to set
	 */
	public void setSerie(String serie) {
		this.serie = serie;
	}


	/**
	 * @return the propietario
	 */
	public String getPropietario() {
		return propietario;
	}


	/**
	 * @param propietario the propietario to set
	 */
	public void setPropietario(String propietario) {
		this.propietario = propietario;
	}


	/**
	 * @return the solicitante
	 */
	public String getSolicitante() {
		return solicitante;
	}


	/**
	 * @param solicitante the solicitante to set
	 */
	public void setSolicitante(String solicitante) {
		this.solicitante = solicitante;
	}
	

}