/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.saldei.web.form.activos;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.ResourceBundle;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import com.saldei.hibernate.tables.activos.ActDetSolicitud;
import com.saldei.hibernate.tables.activos.ActProveedor;
import com.saldei.hibernate.tables.activos.ActSolicitud;
import com.saldei.hibernate.tables.activos.ActSolicitudId;
import com.saldei.hibernate.tables.activos.ActUnidad;
import com.saldei.hibernate.tables.inventario.InvBodega;

/** 
 * MyEclipse Struts
 * Creation date: 06-23-2009
 * 
 * XDoclet definition:
 * @struts.form name="solicitudCompraForm"
 */
public class SolicitudCompraForm extends ActionForm {
	/*
	 * Generated fields
	 */

	SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy H:m:s");
	
	
	/** actSolicitud property */
	private ActSolicitud actSolicitud = new ActSolicitud(new ActSolicitudId(), new ActUnidad());
	private String bodegaDesc;
	private String solicitante;
	private String estadoDesc;
	private String flagCotizaciones;
	private String fechaCrea;
	
	/*
	 * Generated Methods
	 */

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitudId#getCodSolicitud()
	 */
	public String getCodSolicitud() {
		if(this.getId().getCodSolicitud() != null)
			return String.valueOf(this.getId().getCodSolicitud());
		else 
			return "";
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitudId#getTipoSolicitud()
	 */
	public String getTipoSolicitud() {
		return this.getId().getTipoSolicitud();
	}

	/**
	 * @param codSolicitud
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitudId#setCodSolicitud(java.lang.Integer)
	 */
	public void setCodSolicitud(String codSolicitud) {
		if (codSolicitud != null && !codSolicitud.trim().equals(""))
			this.getId().setCodSolicitud(Integer.valueOf(codSolicitud));
	}

	/**
	 * @param tipoSolicitud
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitudId#setTipoSolicitud(java.lang.String)
	 */
	public void setTipoSolicitud(String tipoSolicitud) {
		this.getId().setTipoSolicitud(tipoSolicitud);
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public void validate(ActionMapping mapping,
			HttpServletRequest request, ActionErrors errors) {
		// TODO Auto-generated method stub
		String accion = request.getParameter("accion");
		accion = (accion==null)?"":accion;
		
		ResourceBundle mensajes = ResourceBundle.getBundle("com.saldei.web.ApplicationResources");
		if(!accion.equals(mensajes.getString("opc.cancel")) && !accion.equals(mensajes.getString("opc.find"))){			
			/*if(this.getCodBodega() == null || this.getCodBodega().equals("")){
				errors.add("solCompra.bodega.requerido", new ActionError("solCompra.bodega.requerido"));
			}*/
			
			if(this.getCodUnidad() == null || this.getCodUnidad().trim().equals("")){
				errors.add("solCompra.unidad.requerido", new ActionError("solCompra.unidad.requerido"));
			}
			if(this.getCodBodega() == null || this.getCodBodega().trim().equals("")){
				errors.add("solCompra.bodega.requerido", new ActionError("solCompra.bodega.requerido"));
			}
			if(this.actSolicitud.getComentario() == null || this.actSolicitud.getComentario().trim().equals("")){
				errors.add("suministro.descripcion.requerido", new ActionError("suministro.descripcion.requerido"));
			}
		}				
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		this.actSolicitud = new ActSolicitud(new ActSolicitudId(),new ActUnidad());
		this.bodegaDesc = null;
		this.solicitante = null;
		this.estadoDesc = null;
	}

	/** 
	 * Returns the actSolicitud.
	 * @return ActDetSolicitud
	 */
	public ActSolicitud getActSolicitud() {
		return actSolicitud;
	}

	/** 
	 * Set the actSolicitud.
	 * @param actSolicitud The actSolicitud to set
	 */
	public void setActSolicitud(ActSolicitud actSolicitud) {
		this.actSolicitud = actSolicitud;
	}



	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#getActUnidad()
	 */
	public ActUnidad getActUnidad() {
		return actSolicitud.getActUnidad();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#getCodBodega()
	 */
	public String getCodBodega() {
		if (actSolicitud.getCodBodega() != null)
			return String.valueOf(actSolicitud.getCodBodega());
		else return "";		
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#getCodPropietario()
	 */
	public String getCodPropietario() {
		return actSolicitud.getCodPropietario();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#getCodSolicitante()
	 */
	public String getCodSolicitante() {
		return actSolicitud.getCodSolicitante();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#getComentario()
	 */
	public String getComentario() {
		return actSolicitud.getComentario();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#getEstado()
	 */
	public String getEstado() {
		return actSolicitud.getEstado();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.ActSolicitud#getFecha_fin()
	 */
	public String getFecha_fin() {
		return actSolicitud.getFecha_fin();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.ActSolicitud#getFecha_ini()
	 */
	public String getFecha_ini() {
		return actSolicitud.getFecha_ini();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#getFechaCreacion()
	 */
	public Date getFechaCreacion() {
		return actSolicitud.getFechaCreacion();
	}


	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#getId()
	 */
	public ActSolicitudId getId() {
		return actSolicitud.getId();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.ActSolicitud#getPrestamoLink()
	 */
	public String getLink() {
		String link = " <a  href='#' onclick=\"javascript:enviarSolCompra('Find','"
			+ this.getId().getCodSolicitud()+ "');return false;\" >";
		link += " Detalle de Compra</a>";	
		return link;
	}



	/**
	 * @param actUnidad
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#setActUnidad(com.saldei.hibernate.tables.activos.ActUnidad)
	 */
	public void setActUnidad(ActUnidad actUnidad) {
		actSolicitud.setActUnidad(actUnidad);
	}

	/**
	 * @param codBodega
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#setCodBodega(java.lang.String)
	 */
	public void setCodBodega(String codBodega) {
		if(codBodega != null  && !codBodega.trim().equals(""))
			actSolicitud.setCodBodega(Integer.valueOf(codBodega));
	}

	/**
	 * @param codPropietario
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#setCodPropietario(java.lang.String)
	 */
	public void setCodPropietario(String codPropietario) {
		actSolicitud.setCodPropietario(codPropietario);
	}

	/**
	 * @param codSolicitante
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#setCodSolicitante(java.lang.String)
	 */
	public void setCodSolicitante(String codSolicitante) {
		actSolicitud.setCodSolicitante(codSolicitante);
	}

	/**
	 * @param comentario
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#setComentario(java.lang.String)
	 */
	public void setComentario(String comentario) {
		actSolicitud.setComentario(comentario);
	}

	/**
	 * @param estado
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#setEstado(java.lang.String)
	 */
	public void setEstado(String estado) {
		actSolicitud.setEstado(estado);
	}

	/**
	 * @param fecha_fin
	 * @throws ParseException
	 * @see com.saldei.hibernate.tables.activos.ActSolicitud#setFecha_fin(java.lang.String)
	 */
	public void setFecha_fin(String fecha_fin) throws ParseException {
		actSolicitud.setFecha_fin(fecha_fin);
	}

	/**
	 * @param fecha_ini
	 * @throws ParseException
	 * @see com.saldei.hibernate.tables.activos.ActSolicitud#setFecha_ini(java.lang.String)
	 */
	public void setFecha_ini(String fecha_ini) throws ParseException {
		actSolicitud.setFecha_ini(fecha_ini);
	}

	/**
	 * @param fechaCreacion
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#setFechaCreacion(java.util.Date)
	 */
	public void setFechaCreacion(Date fechaCreacion) {
		actSolicitud.setFechaCreacion(fechaCreacion);
	}
	

	/**
	 * @param id
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#setId(com.saldei.hibernate.tables.activos.ActSolicitudId)
	 */
	public void setId(ActSolicitudId id) {
		actSolicitud.setId(id);
	}



	/**
	 * @return the solicitante
	 */
	public String getSolicitante() {
		return solicitante;
	}

	/**
	 * @param solicitante the solicitante to set
	 */
	public void setSolicitante(String solicitante) {
		this.solicitante = solicitante;
	}

	/**
	 * @return the bodegaDesc
	 */
	public String getBodegaDesc() {
		return bodegaDesc;
	}

	/**
	 * @param bodegaDesc the bodegaDesc to set
	 */
	public void setBodegaDesc(String bodegaDesc) {
		this.bodegaDesc = bodegaDesc;
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActUnidad#getCodUnidad()
	 */
	public String getCodUnidad() {
		if (this.getActUnidad().getCodUnidad() != null)
			return String.valueOf(this.getActUnidad().getCodUnidad());
		else 
			return "";
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActUnidad#getDescripcion()
	 */
	public String getDescripcion() {
		return this.getActUnidad().getDescripcion();
	}

	/**
	 * @param codUnidad
	 * @see com.saldei.hibernate.tables.activos.AbstractActUnidad#setCodUnidad(java.lang.Integer)
	 */
	public void setCodUnidad(String codUnidad) {
		if(codUnidad != null && !codUnidad.trim().equals(""))
			this.getActUnidad().setCodUnidad(Integer.valueOf(codUnidad));
	}

	/**
	 * @param descripcion
	 * @see com.saldei.hibernate.tables.activos.AbstractActUnidad#setDescripcion(java.lang.String)
	 */
	public void setDescripcion(String descripcion) {
		this.getActUnidad().setDescripcion(descripcion);
	}

	/**
	 * @return the estadoDesc
	 */
	public String getEstadoDesc() {
		return estadoDesc;
	}

	/**
	 * @param estadoDesc the estadoDesc to set
	 */
	public void setEstadoDesc(String estadoDesc) {
		this.estadoDesc = estadoDesc;
	}
	
	public String getFechaCrea() {
		if(this.getFechaCreacion() != null)
			return sdf.format(this.getFechaCreacion());
		else return "";
	}

	/**
	 * @return the flagDetalleCotizacion
	 */
	public String getFlagCotizaciones() {
		return flagCotizaciones;
	}

	/**
	 * @param flagDetalleCotizacion the flagDetalleCotizacion to set
	 */
	public void setFlagCotizaciones(String flagCotizaciones) {
		this.flagCotizaciones = flagCotizaciones;
	}


	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.ActSolicitud#getDesBodega()
	 */
	public String getDesBodega() {
		return actSolicitud.getDesBodega();
	}

	/**
	 * @param codBodega
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#setCodBodega(java.lang.Integer)
	 */
	public void setCodBodega(Integer codBodega) {
		actSolicitud.setCodBodega(codBodega);
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#getAsigCompra()
	 */
	public String getAsigCompra() {
		return actSolicitud.getAsigCompra();
	}

	/**
	 * @param asigCompra
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#setAsigCompra(java.lang.String)
	 */
	public void setAsigCompra(String asigCompra) {
		actSolicitud.setAsigCompra(asigCompra);
	}

	
}
