/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.saldei.web.form.seguridad;

import java.util.ResourceBundle;
import java.util.Set;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.saldei.hibernate.tables.Opcion;
import com.saldei.hibernate.tables.seguridad.OpcionSeguridad;

/** 
 * MyEclipse Struts
 * Creation date: 08-06-2009
 * 
 * XDoclet definition:
 * @struts.form name="mtoOpcionForm"
 */
public class MtoOpcionForm extends ActionForm {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	private Opcion opcion= new Opcion();
	private OpcionSeguridad opcionSeguridad = new OpcionSeguridad();
	private String opcionPadre;
	private Integer idOpcionSeguridad;
	private String estadoDescr;
	private String separador;
	private String visibleDescr;
	
	/**
	 * @return
	 * @see com.saldei.hibernate.tables.seguridad.AbstractOpcionSeguridad#getVisible()
	 */
	public String getVisible() {
		return opcionSeguridad.getVisible();
	}

	/**
	 * @param visible
	 * @see com.saldei.hibernate.tables.seguridad.AbstractOpcionSeguridad#setVisible(java.lang.String)
	 */
	public void setVisible(String visible) {
		opcionSeguridad.setVisible(visible);
	}

	@SuppressWarnings("deprecation")
		public void validate(ActionMapping mapping,
			HttpServletRequest request, ActionErrors errors) {
		// TODO Auto-generated method stub
		String accion = request.getParameter("accion");
		accion = (accion==null)?"":accion;
		
		ResourceBundle mensajes = ResourceBundle.getBundle("com.saldei.web.ApplicationResources");
		if(!accion.equals(mensajes.getString("opc.cancel")) && !accion.equals(mensajes.getString("opc.find"))){
			if(this.getNomOpcion() == null || this.getNomOpcion().equals(""))
				errors.add("mopc.nomOpcion.requerido", new ActionError("mopc.nomOpcion.requerido"));
			if(this.getDescOpcion() == null || this.getDescOpcion().equals(""))
				errors.add("mopc.descOpcion.requerido", new ActionError("mopc.descOpcion.requerido"));
			if(this.getUrlOpcion() == null || this.getUrlOpcion().equals(""))
				errors.add("mopc.urlOpcion.requerido", new ActionError("mopc.urlOpcion.requerido"));
			if(this.getOrden() == null || this.getOrden() < 0 )
				errors.add("mopc.orden.requerido", new ActionError("mopc.orden.requerido"));
			if(this.getMetodo() == null || this.getMetodo().equals("") )
				errors.add("mopc.metodo.requerido", new ActionError("mopc.metodo.requerido"));
			
		}				
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		opcion= new Opcion();
		opcionSeguridad = new OpcionSeguridad();
		this.setDescOpcion("");
		this.setOpcionPadre("");
		
		
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.Opcion#getDescOpcion()
	 */
	public String getDescOpcion() {
		return opcion.getDescOpcion();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.Opcion#getEstOpcion()
	 */
	public String getEstOpcion() {
		return opcion.getEstOpcion();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.Opcion#getIdOpcion()
	 */
	public Integer getIdOpcion() {
		return opcion.getIdOpcion();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.Opcion#getIdOpcionPadre()
	 */
	public Integer getIdOpcionPadre() {
		return opcion.getIdOpcionPadre();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.Opcion#getIsSeparador()
	 */
	public String getIsSeparador() {
		return opcion.getIsSeparador();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.Opcion#getMetodo()
	 */
	public String getMetodo() {
		return opcion.getMetodo();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.Opcion#getNomOpcion()
	 */
	public String getNomOpcion() {
		return opcion.getNomOpcion();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.Opcion#getOpcionPerfils()
	 */
	public Set getOpcionPerfils() {
		return opcion.getOpcionPerfils();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.Opcion#getOrden()
	 */
	public Long getOrden() {
		return opcion.getOrden();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.Opcion#getUrlOpcion()
	 */
	public String getUrlOpcion() {
		return opcion.getUrlOpcion();
	}

	/**
	 * @param descOpcion
	 * @see com.saldei.hibernate.tables.Opcion#setDescOpcion(java.lang.String)
	 */
	public void setDescOpcion(String descOpcion) {
		opcion.setDescOpcion(descOpcion);
	}

	/**
	 * @param estOpcion
	 * @see com.saldei.hibernate.tables.Opcion#setEstOpcion(java.lang.String)
	 */
	public void setEstOpcion(String estOpcion) {
		opcion.setEstOpcion(estOpcion);
	}

	/**
	 * @param idOpcion
	 * @see com.saldei.hibernate.tables.Opcion#setIdOpcion(java.lang.Integer)
	 */
	public void setIdOpcion(Integer idOpcion) {
		opcion.setIdOpcion(idOpcion);
	}

	/**
	 * @param idOpcionPadre
	 * @see com.saldei.hibernate.tables.Opcion#setIdOpcionPadre(java.lang.Integer)
	 */
	public void setIdOpcionPadre(Integer idOpcionPadre) {
		opcion.setIdOpcionPadre(idOpcionPadre);
	}

	/**
	 * @param isSeparador
	 * @see com.saldei.hibernate.tables.Opcion#setIsSeparador(java.lang.String)
	 */
	public void setIsSeparador(String isSeparador) {
		opcion.setIsSeparador(isSeparador);
	}

	/**
	 * @param metodo
	 * @see com.saldei.hibernate.tables.Opcion#setMetodo(java.lang.String)
	 */
	public void setMetodo(String metodo) {
		opcion.setMetodo(metodo);
	}

	/**
	 * @param nomOpcion
	 * @see com.saldei.hibernate.tables.Opcion#setNomOpcion(java.lang.String)
	 */
	public void setNomOpcion(String nomOpcion) {
		opcion.setNomOpcion(nomOpcion);
	}

	/**
	 * @param opcionPerfils
	 * @see com.saldei.hibernate.tables.Opcion#setOpcionPerfils(java.util.Set)
	 */
	public void setOpcionPerfils(Set opcionPerfils) {
		opcion.setOpcionPerfils(opcionPerfils);
	}

	/**
	 * @param orden
	 * @see com.saldei.hibernate.tables.Opcion#setOrden(java.lang.Long)
	 */
	public void setOrden(Long orden) {
		opcion.setOrden(orden);
	}

	/**
	 * @param urlOpcion
	 * @see com.saldei.hibernate.tables.Opcion#setUrlOpcion(java.lang.String)
	 */
	public void setUrlOpcion(String urlOpcion) {
		opcion.setUrlOpcion(urlOpcion);
	}

	/**
	 * @return the opcion
	 */
	public Opcion getOpcion() {
		return opcion;
	}

	/**
	 * @param opcion the opcion to set
	 */
	public void setOpcion(Opcion opcion) {
		this.opcion = opcion;
	}

	/**
	 * @return the opcionSeguridad
	 */
	public OpcionSeguridad getOpcionSeguridad() {
		return opcionSeguridad;
	}

	/**
	 * @param opcionSeguridad the opcionSeguridad to set
	 */
	public void setOpcionSeguridad(OpcionSeguridad opcionSeguridad) {
		this.opcionSeguridad = opcionSeguridad;
	}

	/**
	 * @return the opcionPadre
	 */
	public String getOpcionPadre() {
		return opcionPadre;
	}

	/**
	 * @param opcionPadre the opcionPadre to set
	 */
	public void setOpcionPadre(String opcionPadre) {
		this.opcionPadre = opcionPadre;
	}

	/**
	 * @return the idOpcionSeguridad
	 */
	public Integer getIdOpcionSeguridad() {
		return opcionSeguridad.getIdOpcion();
	}

	/**
	 * @param idOpcionSeguridad the idOpcionSeguridad to set
	 */
	public void setIdOpcionSeguridad(Integer idOpcionSeguridad) {
		opcionSeguridad.setIdOpcion(idOpcionSeguridad);
	}

	/**
	 * @return the estadoDescr
	 */
	public String getEstadoDescr() {
		if(opcion.getEstOpcion().equals("A"))
			return "Activo";
		else
			return "Inactivo";
	}

	/**
	 * @param estadoDescr the estadoDescr to set
	 */
	public void setEstadoDescr(String estadoDescr) {
		if(opcion.getEstOpcion().equals("A"))
			this.estadoDescr = "Activo";
		else
			this.estadoDescr = "Inactivo";
	}

	/**
	 * @return the separador
	 */
	public String getSeparador() {
		return separador;
	}

	/**
	 * @param separador the separador to set
	 */
	public void setSeparador(String separador) {
		this.separador = separador;
	}

	/**
	 * @return the visibleDescr
	 */
	public String getVisibleDescr() {
		return visibleDescr;
	}

	/**
	 * @param visibleDescr the visibleDescr to set
	 */
	public void setVisibleDescr(String visibleDescr) {
		this.visibleDescr = visibleDescr;
	}
}