/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.saldei.web.form.seguridad;

import java.util.ResourceBundle;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.saldei.hibernate.tables.Usuario;
import com.saldei.hibernate.tables.UsuarioDei;
import com.saldei.hibernate.tables.UsuarioTitulo;

/** 
 * MyEclipse Struts
 * Creation date: 07-17-2009
 * 
 * XDoclet definition:
 * @struts.form name="usuarioTituloForm"
 */
public class UsuarioTituloForm extends ActionForm {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	
	//public Usuario(String idUsuario, String pswUsuario, String primerNom, String primerApe, String sex, Integer estadoCivil, String email, String estUsuario)
	private UsuarioTitulo usuarioTitulo = new UsuarioTitulo(new UsuarioDei("",new Usuario("","","","","",0,"","")));
	private String codResponsable;
	private String responsableDescr;
	private String porDefectoDescr;
	private String idUsuario;
	private Integer correlativo;
	
	
	
	/**
	 * @return
	 * @see com.saldei.hibernate.tables.AbstractUsuarioTitulo#getAbvTitulo()
	 */
	public String getAbvTitulo() {
		return usuarioTitulo.getAbvTitulo();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.AbstractUsuarioTitulo#getId()
	 */
	

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.AbstractUsuarioTitulo#getPorDefecto()
	 */
	public String getPorDefecto() {
		return usuarioTitulo.getPorDefecto();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.AbstractUsuarioTitulo#getTitulo()
	 */
	public String getTitulo() {
		return usuarioTitulo.getTitulo();
	}

	/**
	 * @param abvTitulo
	 * @see com.saldei.hibernate.tables.AbstractUsuarioTitulo#setAbvTitulo(java.lang.String)
	 */
	public void setAbvTitulo(String abvTitulo) {
		usuarioTitulo.setAbvTitulo(abvTitulo);
	}

	/**
	 * @param id
	 * @see com.saldei.hibernate.tables.AbstractUsuarioTitulo#setId(com.saldei.hibernate.tables.UsuarioTituloId)
	 */


	/**
	 * @param porDefecto
	 * @see com.saldei.hibernate.tables.AbstractUsuarioTitulo#setPorDefecto(java.lang.String)
	 */
	public void setPorDefecto(String porDefecto) {
		usuarioTitulo.setPorDefecto(porDefecto);
	}

	/**
	 * @param titulo
	 * @see com.saldei.hibernate.tables.AbstractUsuarioTitulo#setTitulo(java.lang.String)
	 */
	public void setTitulo(String titulo) {
		usuarioTitulo.setTitulo(titulo);
	}

	public void validate(ActionMapping mapping,
			HttpServletRequest request, ActionErrors errors) {
		//TODO Auto-generated method stub
	String accion = request.getParameter("accion");
	accion = (accion==null)?"":accion;
		
		ResourceBundle mensajes = ResourceBundle.getBundle("com.saldei.web.ApplicationResources");
		if(!accion.equals(mensajes.getString("opc.cancel")) && !accion.equals(mensajes.getString("opc.find"))){
			if(this.getCodResponsable() == null || this.getCodResponsable().equals(""))
				errors.add("uti.usuario.requerido", new ActionError("uti.usuario.requerido"));
			if(this.getTitulo() == null || this.getTitulo().equals(""))
				errors.add("uti.titulo.requerido", new ActionError("uti.titulo.requerido"));
		}			
	}
	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		usuarioTitulo = new UsuarioTitulo(new UsuarioDei("",new Usuario("","","","","",0,"","")));
		this.setResponsableDescr("");
		this.setPorDefectoDescr("");
	}

	/**
	 * @return the usuarioTitulo
	 */
	public UsuarioTitulo getUsuarioTitulo() {
		return usuarioTitulo;
	}

	/**
	 * @param usuarioTitulo the usuarioTitulo to set
	 */
	public void setUsuarioTitulo(UsuarioTitulo usuarioTitulo) {
		this.usuarioTitulo = usuarioTitulo;
	}

	/**
	 * @return the idUsuario
	 */


	/**
	 * @return the codResponsable
	 */
	public String getCodResponsable() {
		return codResponsable;
	}

	/**
	 * @param codResponsable the codResponsable to set
	 */
	public void setCodResponsable(String codResponsable) {
		this.codResponsable = codResponsable;
	}

	/**
	 * @return the responsableDescr
	 */
	public String getResponsableDescr() {
		return responsableDescr;
	}

	/**
	 * @param responsableDescr the responsableDescr to set
	 */
	public void setResponsableDescr(String responsableDescr) {
		this.responsableDescr = responsableDescr;
	}

	/**
	 * @return the porDefectoDescr
	 */
	public String getPorDefectoDescr() {
		return porDefectoDescr;
	}

	/**
	 * @param porDefectoDescr the porDefectoDescr to set
	 */
	public void setPorDefectoDescr(String porDefectoDescr) {
		this.porDefectoDescr = porDefectoDescr;
	}

	public String getIdUsuario() {
		return usuarioTitulo.getUsuarioDei().getUsuario().getIdUsuario();
	}

	public void setIdUsuario(String idUsuario) {
		usuarioTitulo.getUsuarioDei().getUsuario().setIdUsuario(idUsuario);
		usuarioTitulo.getUsuarioDei().setCodigoEmpleado(idUsuario);
	}

	public Integer getCorrelativo() {
		return usuarioTitulo.getCorrelativo();
	}

	public void setCorrelativo(Integer correlativo) {
		usuarioTitulo.setCorrelativo(correlativo);
		
	}
}