/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.saldei.web.form.inventario;

import java.util.ResourceBundle;
import java.util.Set;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.saldei.hibernate.tables.inventario.InvBodega;

/** 
 * MyEclipse Struts
 * Creation date: 05-27-2009
 * 
 * XDoclet definition:
 * @struts.form name="bodegaForm"
 */
public class BodegaForm extends ActionForm {
	/*
	 * Generated fields
	 */
	private String estadoNombre;
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private InvBodega invBodega = new InvBodega();

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */


	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void validate(ActionMapping mapping,
			HttpServletRequest request, ActionErrors errors) {
		// TODO Auto-generated method stub
		String accion = request.getParameter("accion");
		accion = (accion==null)?"":accion;
		
		ResourceBundle mensajes = ResourceBundle.getBundle("com.saldei.web.ApplicationResources");
		if(!accion.equals(mensajes.getString("opc.cancel")) && !accion.equals(mensajes.getString("opc.find"))){
			if(this.getCodBodega() == null || this.getCodBodega().trim().equals("")){
				errors.add("bode.codigo.requerido", new ActionError("bode.codigo.requerido"));
			}
			if(this.getNombre() == null || this.getNombre().trim().equals("")){
				errors.add("bode.nombre.requerido", new ActionError("bode.nombre.requerido"));
			}
		}				
	}
	
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		/*this.setCodBodega(null);
		this.setNombre(null);
		this.setUbicacion(null);*/
		
		invBodega = new InvBodega();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.inventario.AbstractInvBodega#getCodBodega()
	 */
	public String getCodBodega() {
		if (invBodega.getCodBodega() != null)
			return String.valueOf(invBodega.getCodBodega());
		else return "";		
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.inventario.AbstractInvBodega#getInvExistencias()
	 */
	public Set getInvExistencias() {
		return invBodega.getInvExistencias();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.inventario.AbstractInvBodega#getInvMovimientos()
	 */
	public Set getInvMovimientos() {
		return invBodega.getInvMovimientos();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.inventario.AbstractInvBodega#getNombre()
	 */
	public String getNombre() {
		return invBodega.getNombre();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.inventario.AbstractInvBodega#getUbicacion()
	 */
	public String getUbicacion() {
		return invBodega.getUbicacion();
	}

	/**
	 * @param codBodega
	 * @see com.saldei.hibernate.tables.inventario.AbstractInvBodega#setCodBodega(java.lang.String)
	 */
	public void setCodBodega(String codBodega) {
		if(codBodega != null  && !codBodega.trim().equals(""))
			invBodega.setCodBodega(Integer.valueOf(codBodega));
	}

	/**
	 * @param invExistencias
	 * @see com.saldei.hibernate.tables.inventario.AbstractInvBodega#setInvExistencias(java.util.Set)
	 */
	public void setInvExistencias(Set invExistencias) {
		invBodega.setInvExistencias(invExistencias);
	}

	/**
	 * @param invMovimientos
	 * @see com.saldei.hibernate.tables.inventario.AbstractInvBodega#setInvMovimientos(java.util.Set)
	 */
	public void setInvMovimientos(Set invMovimientos) {
		invBodega.setInvMovimientos(invMovimientos);
	}

	/**
	 * @param nombre
	 * @see com.saldei.hibernate.tables.inventario.AbstractInvBodega#setNombre(java.lang.String)
	 */
	public void setNombre(String nombre) {
		invBodega.setNombre(nombre);
	}

	/**
	 * @param ubicacion
	 * @see com.saldei.hibernate.tables.inventario.AbstractInvBodega#setUbicacion(java.lang.String)
	 */
	public void setUbicacion(String ubicacion) {
		invBodega.setUbicacion(ubicacion);
	}

	/**
	 * @return the invBodega
	 */
	public InvBodega getInvBodega() {
		return invBodega;
	}

	/**
	 * @param invBodega the invBodega to set
	 */
	public void setInvBodega(InvBodega invBodega) {
		this.invBodega = invBodega;
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.inventario.AbstractInvBodega#getEstado()
	 */
	public String getEstado() {
		return invBodega.getEstado();
	}

	/**
	 * @param estado
	 * @see com.saldei.hibernate.tables.inventario.AbstractInvBodega#setEstado(java.lang.String)
	 */
	public void setEstado(String estado) {
		invBodega.setEstado(estado);
	}

	/**
	 * @return
	 * @see java.lang.Object#toString()
	 */
	public String toString() {
		return invBodega.toString();
	}

	/**
	 * @return the estadoNombre
	 */
	public String getEstadoNombre() {
		return estadoNombre;
	}

	/**
	 * @param estadoNombre the estadoNombre to set
	 */
	public void setEstadoNombre(String estadoNombre) {
		this.estadoNombre = estadoNombre;
	}

	/** 
	 * Returns the nombre.
	 * @return String
	 */
	
}