/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.saldei.web.form.inventario;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import com.saldei.hibernate.tables.activos.ActSolicitud;
import com.saldei.hibernate.tables.activos.ActSolicitudId;

/** 
 * MyEclipse Struts
 * Creation date: 08-08-2009
 * 
 * XDoclet definition:
 * @struts.form name="salSolRecursoForm"
 */
public class SalSolRecursoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** actSolicitud property */
	private ActSolicitud actSolicitud =  new ActSolicitud(new ActSolicitudId());
	private String solicitante;	
	private String[] cantidadIngresar;
	private String[] seriesIngresadas;
	private String[] seriesIngresar;
	private String mostrarHistorico;
	//private ActSolicitudId actSolicitudId;
	/*
	 * Generated Methods
	 */

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.ActSolicitud#getNombre()
	 */
	public String getNombre() {
		return actSolicitud.getNombre();
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public void  validate(ActionMapping mapping,
			HttpServletRequest request,ActionErrors errors) {
		// TODO Auto-generated method stub		
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the actSolicitud.
	 * @return ActSolicitud
	 */
	public ActSolicitud getActSolicitud() {
		return actSolicitud;
	}

	/** 
	 * Set the actSolicitud.
	 * @param actSolicitud The actSolicitud to set
	 */
	public void setActSolicitud(ActSolicitud actSolicitud) {
		this.actSolicitud = actSolicitud;
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#getCodSolicitante()
	 */
	public String getCodSolicitante() {
		return actSolicitud.getCodSolicitante();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#getEstado()
	 */
	public String getEstado() {
		return actSolicitud.getEstado();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.ActSolicitud#getEstadoDesc()
	 */
	public String getEstadoDesc() {
		return actSolicitud.getEstadoDesc();
	}

	/**
	 * @param codSolicitante
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#setCodSolicitante(java.lang.String)
	 */
	public void setCodSolicitante(String codSolicitante) {
		actSolicitud.setCodSolicitante(codSolicitante);
	}

	/**
	 * @param estado
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#setEstado(java.lang.String)
	 */
	public void setEstado(String estado) {
		actSolicitud.setEstado(estado);
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitudId#getCodSolicitud()
	 */
	public Integer getCodSolicitud() {
		return this.actSolicitud.getId().getCodSolicitud();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitudId#getTipoSolicitud()
	 */
	public String getTipoSolicitud() {
		return this.actSolicitud.getId().getTipoSolicitud();
	}

	/**
	 * @param codSolicitud
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitudId#setCodSolicitud(java.lang.Integer)
	 */
	public void setCodSolicitud(Integer codSolicitud) {
		this.actSolicitud.getId().setCodSolicitud(codSolicitud);
	}

	/**
	 * @param tipoSolicitud
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitudId#setTipoSolicitud(java.lang.String)
	 */
	public void setTipoSolicitud(String tipoSolicitud) {
		this.actSolicitud.getId().setTipoSolicitud(tipoSolicitud);
	}

	/**
	 * @return the solicitante
	 */
	public String getSolicitante() {
		return solicitante;
	}

	/**
	 * @param solicitante the solicitante to set
	 */
	public void setSolicitante(String solicitante) {
		this.solicitante = solicitante;
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#getComentario()
	 */
	public String getComentario() {
		return actSolicitud.getComentario();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#getMotivoRechazo()
	 */
	public String getMotivoRechazo() {
		return actSolicitud.getMotivoRechazo();
	}

	/**
	 * @param comentario
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#setComentario(java.lang.String)
	 */
	public void setComentario(String comentario) {
		actSolicitud.setComentario(comentario);
	}

	/**
	 * @param motivoRechazo
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#setMotivoRechazo(java.lang.String)
	 */
	public void setMotivoRechazo(String motivoRechazo) {
		actSolicitud.setMotivoRechazo(motivoRechazo);
	}
	
	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActUnidad#getDescripcion()
	 */
	public String getDescripcion() {
		return this.actSolicitud.getActUnidad().getDescripcion();
	}

	/**
	 * @param descripcion
	 * @see com.saldei.hibernate.tables.activos.AbstractActUnidad#setDescripcion(java.lang.String)
	 */
	public void setDescripcion(String descripcion) {
		this.actSolicitud.getActUnidad().setDescripcion(descripcion);
	}

	/**
	 * @return the cantidadIngresar
	 */
	public String[] getCantidadIngresar() {
		return cantidadIngresar;
	}

	/**
	 * @param cantidadIngresar the cantidadIngresar to set
	 */
	public void setCantidadIngresar(String[] cantidadIngresar) {
		this.cantidadIngresar = cantidadIngresar;
	}

	/**
	 * @return the seriesIngresadas
	 */
	public String[] getSeriesIngresadas() {
		return seriesIngresadas;
	}

	/**
	 * @param seriesIngresadas the seriesIngresadas to set
	 */
	public void setSeriesIngresadas(String[] seriesIngresadas) {
		this.seriesIngresadas = seriesIngresadas;
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#getCodBodega()
	 */
	public Integer getCodBodega() {
		return actSolicitud.getCodBodega();
	}

	/**
	 * @return
	 * @see com.saldei.hibernate.tables.activos.ActSolicitud#getDesBodega()
	 */
	public String getDesBodega() {
		return actSolicitud.getDesBodega();
	}

	/**
	 * @param codBodega
	 * @see com.saldei.hibernate.tables.activos.AbstractActSolicitud#setCodBodega(java.lang.Integer)
	 */
	public void setCodBodega(Integer codBodega) {
		actSolicitud.setCodBodega(codBodega);
	}

	/**
	 * @return the seriesIngresar
	 */
	public String[] getSeriesIngresar() {
		return seriesIngresar;
	}

	/**
	 * @param seriesIngresar the seriesIngresar to set
	 */
	public void setSeriesIngresar(String[] seriesIngresar) {
		this.seriesIngresar = seriesIngresar;
	}

	/**
	 * @return the mostrarHistorico
	 */
	public String getMostrarHistorico() {
		return mostrarHistorico;
	}

	/**
	 * @param mostrarHistorico the mostrarHistorico to set
	 */
	public void setMostrarHistorico(String mostrarHistorico) {
		this.mostrarHistorico = mostrarHistorico;
	}
}