package com.saldei.hibernate.tables.activos;

/**
 * AbstractActDetCotizacion generated by MyEclipse Persistence Tools
 */

public abstract class AbstractActDetCotizacion implements java.io.Serializable {

	// Fields

	private ActDetCotizacionId id;
	private double precioUnitario;
	private Integer cantidad;
	private double precioUnitarioIva;

	// Constructors

	/** default constructor */
	public AbstractActDetCotizacion() {
	}

	/** minimal constructor */
	public AbstractActDetCotizacion(ActDetCotizacionId id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractActDetCotizacion(ActDetCotizacionId id,
			double precioUnitario, Integer cantidad, double precioUnitarioIva) {
		this.id = id;
		this.precioUnitario = precioUnitario;
		this.cantidad = cantidad;
		this.precioUnitarioIva = precioUnitarioIva;
	}

	// Property accessors

	public ActDetCotizacionId getId() {
		return this.id;
	}

	public void setId(ActDetCotizacionId id) {
		this.id = id;
	}

	public double getPrecioUnitario() {
		return this.precioUnitario;
	}

	public void setPrecioUnitario(double precioUnitario) {
		this.precioUnitario = precioUnitario;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	public double getPrecioUnitarioIva() {
		return this.precioUnitarioIva;
	}

	public void setPrecioUnitarioIva(double precioUnitarioIva) {
		this.precioUnitarioIva = precioUnitarioIva;
	}

}
