package com.saldei.hibernate.tables.activos;

import java.util.HashSet;
import java.util.Set;

/**
 * AbstractActEstadoActivo generated by MyEclipse Persistence Tools
 */

public abstract class AbstractActEstadoActivo implements java.io.Serializable {

	// Fields

	private Integer codEstado;
	private String descripcion;
	private Set actActivos = new HashSet(0);

	// Constructors

	/** default constructor */
	public AbstractActEstadoActivo() {
	}

	/** full constructor */
	public AbstractActEstadoActivo(String descripcion, Set actActivos) {
		this.descripcion = descripcion;
		this.actActivos = actActivos;
	}

	// Property accessors

	public Integer getCodEstado() {
		return this.codEstado;
	}

	public void setCodEstado(Integer codEstado) {
		this.codEstado = codEstado;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getActActivos() {
		return this.actActivos;
	}

	public void setActActivos(Set actActivos) {
		this.actActivos = actActivos;
	}

}