package com.saldei.hibernate.tables.activos;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * ActHistUnidadActivo generated by MyEclipse Persistence Tools
 */
public class ActHistUnidadActivo extends AbstractActHistUnidadActivo implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public ActHistUnidadActivo() {
	}

	/**
	 * @param correlativo
	 * @param actUnidad
	 * @param actActivo
	 * @param fechaCreacion
	 * @param creadoPor
	 */
	public ActHistUnidadActivo(Integer correlativo, ActUnidad actUnidad,
			ActActivo actActivo, Date fechaCreacion, String creadoPor) {
		super(correlativo, actUnidad, actActivo, fechaCreacion, creadoPor);
		// TODO Auto-generated constructor stub
	}

	/**
	 * @param correlativo
	 * @param actActivo
	 */
	public ActHistUnidadActivo(Integer correlativo, ActActivo actActivo) {
		super(correlativo, actActivo);
		// TODO Auto-generated constructor stub
	}

}
