package com.saldei.hibernate.tables;

import java.util.Date;


/**
 * Auditoria generated by MyEclipse - Hibernate Tools
 */

public class Auditoria  implements java.io.Serializable {


    // Fields    

     private Integer idAuditoria;
     private String idUsuario;
     private Date fechaAccion;
     private String nomTabla;
     private String accion;
     private String llavePrimaria;


    // Constructors

    /** default constructor */
    public Auditoria() {
    }

    
    /** full constructor */
    public Auditoria(Integer idAuditoria, String idUsuario, Date fechaAccion, String nomTabla, String accion, String llavePrimaria) {
        this.idAuditoria = idAuditoria;
        this.idUsuario = idUsuario;
        this.fechaAccion = fechaAccion;
        this.nomTabla = nomTabla;
        this.accion = accion;
        this.llavePrimaria = llavePrimaria;
    }

   
    // Property accessors

    public Integer getIdAuditoria() {
        return this.idAuditoria;
    }
    
    public void setIdAuditoria(Integer idAuditoria) {
        this.idAuditoria = idAuditoria;
    }

    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }

    public Date getFechaAccion() {
        return this.fechaAccion;
    }
    
    public void setFechaAccion(Date fechaAccion) {
        this.fechaAccion = fechaAccion;
    }

    public String getNomTabla() {
        return this.nomTabla;
    }
    
    public void setNomTabla(String nomTabla) {
        this.nomTabla = nomTabla;
    }

    public String getAccion() {
        return this.accion;
    }
    
    public void setAccion(String accion) {
        this.accion = accion;
    }

    public String getLlavePrimaria() {
        return this.llavePrimaria;
    }
    
    public void setLlavePrimaria(String llavePrimaria) {
        this.llavePrimaria = llavePrimaria;
    }
   








}