package com.saldei.hibernate.tables;

import java.util.Date;


/**
 * CargoUsuarioDei generated by MyEclipse - Hibernate Tools
 */

public class CargoUsuarioDei  implements java.io.Serializable {


    // Fields    

     private Integer idCargoUsr;
     private Usuario usuario;
     private Integer idCargo;
     private Date fechaIni;
     private Date fechaFin;
     private String estCargoDei;


    // Constructors

    /** default constructor */
    public CargoUsuarioDei() {
    }

    
    /** full constructor */
    public CargoUsuarioDei(Integer idCargoUsr, Usuario usuario, Integer idCargo, Date fechaIni, Date fechaFin, String estCargoDei) {
        this.idCargoUsr = idCargoUsr;
        this.usuario = usuario;
        this.idCargo = idCargo;
        this.fechaIni = fechaIni;
        this.fechaFin = fechaFin;
        this.estCargoDei = estCargoDei;
    }

   
    // Property accessors

    public Integer getIdCargoUsr() {
        return this.idCargoUsr;
    }
    
    public void setIdCargoUsr(Integer idCargoUsr) {
        this.idCargoUsr = idCargoUsr;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public Integer getIdCargo() {
        return this.idCargo;
    }
    
    public void setIdCargo(Integer idCargo) {
        this.idCargo = idCargo;
    }

    public Date getFechaIni() {
        return this.fechaIni;
    }
    
    public void setFechaIni(Date fechaIni) {
        this.fechaIni = fechaIni;
    }

    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    public String getEstCargoDei() {
        return this.estCargoDei;
    }
    
    public void setEstCargoDei(String estCargoDei) {
        this.estCargoDei = estCargoDei;
    }
   








}