package com.saldei.hibernate.tables;

import java.util.HashSet;
import java.util.Set;


/**
 * CatedraticoMateria generated by MyEclipse - Hibernate Tools
 */

public class CatedraticoMateria  implements java.io.Serializable {


    // Fields    

     private CatedraticoMateriaId id;
     private String estCatMat;
     private Set solicitudReqMats = new HashSet(0);


    // Constructors

    /** default constructor */
    public CatedraticoMateria() {
    }

	/** minimal constructor */
    public CatedraticoMateria(CatedraticoMateriaId id, String estCatMat) {
        this.id = id;
        this.estCatMat = estCatMat;
    }
    
    /** full constructor */
    public CatedraticoMateria(CatedraticoMateriaId id, String estCatMat, Set solicitudReqMats) {
        this.id = id;
        this.estCatMat = estCatMat;
        this.solicitudReqMats = solicitudReqMats;
    }

   
    // Property accessors

    public CatedraticoMateriaId getId() {
        return this.id;
    }
    
    public void setId(CatedraticoMateriaId id) {
        this.id = id;
    }

    public String getEstCatMat() {
        return this.estCatMat;
    }
    
    public void setEstCatMat(String estCatMat) {
        this.estCatMat = estCatMat;
    }

    public Set getSolicitudReqMats() {
        return this.solicitudReqMats;
    }
    
    public void setSolicitudReqMats(Set solicitudReqMats) {
        this.solicitudReqMats = solicitudReqMats;
    }
   








}