package com.saldei.hibernate.tables;

import java.util.HashSet;
import java.util.Set;


/**
 * Materia generated by MyEclipse - Hibernate Tools
 */

public class Materia  implements java.io.Serializable {


    // Fields    

     private Integer idMateria;
     private String codMateria;
     private String nomMateria;
     private String descMateria;
     private Integer uniValorativas;
     private String estMateria;
     private Set materiaCiclos = new HashSet(0);


    // Constructors

    /** default constructor */
    public Materia() {
    }

	/** minimal constructor */
    public Materia(Integer idMateria, String codMateria, String nomMateria, Integer uniValorativas, String estMateria) {
        this.idMateria = idMateria;
        this.codMateria = codMateria;
        this.nomMateria = nomMateria;
        this.uniValorativas = uniValorativas;
        this.estMateria = estMateria;
    }
    
    /** full constructor */
    public Materia(Integer idMateria, String codMateria, String nomMateria, String descMateria, Integer uniValorativas, String estMateria, Set materiaCiclos) {
        this.idMateria = idMateria;
        this.codMateria = codMateria;
        this.nomMateria = nomMateria;
        this.descMateria = descMateria;
        this.uniValorativas = uniValorativas;
        this.estMateria = estMateria;
        this.materiaCiclos = materiaCiclos;
    }

   
    // Property accessors

    public Integer getIdMateria() {
        return this.idMateria;
    }
    
    public void setIdMateria(Integer idMateria) {
        this.idMateria = idMateria;
    }

    public String getCodMateria() {
        return this.codMateria;
    }
    
    public void setCodMateria(String codMateria) {
        this.codMateria = codMateria;
    }

    public String getNomMateria() {
        return this.nomMateria;
    }
    
    public void setNomMateria(String nomMateria) {
        this.nomMateria = nomMateria;
    }

    public String getDescMateria() {
        return this.descMateria;
    }
    
    public void setDescMateria(String descMateria) {
        this.descMateria = descMateria;
    }

    public Integer getUniValorativas() {
        return this.uniValorativas;
    }
    
    public void setUniValorativas(Integer uniValorativas) {
        this.uniValorativas = uniValorativas;
    }

    public String getEstMateria() {
        return this.estMateria;
    }
    
    public void setEstMateria(String estMateria) {
        this.estMateria = estMateria;
    }

    public Set getMateriaCiclos() {
        return this.materiaCiclos;
    }
    
    public void setMateriaCiclos(Set materiaCiclos) {
        this.materiaCiclos = materiaCiclos;
    }
   








}