package com.saldei.hibernate.tables;

import java.util.HashSet;
import java.util.Set;


/**
 * MateriaCiclo generated by MyEclipse - Hibernate Tools
 */

public class MateriaCiclo  implements java.io.Serializable {


    // Fields    

     private MateriaCicloId id;
     private String estMatCiclo;
     private Set materiaInscritas = new HashSet(0);
     private Set catedraticoMaterias = new HashSet(0);


    // Constructors

    /** default constructor */
    public MateriaCiclo() {
    }

	/** minimal constructor */
    public MateriaCiclo(MateriaCicloId id, String estMatCiclo) {
        this.id = id;
        this.estMatCiclo = estMatCiclo;
    }
    
    /** full constructor */
    public MateriaCiclo(MateriaCicloId id, String estMatCiclo, Set materiaInscritas, Set catedraticoMaterias) {
        this.id = id;
        this.estMatCiclo = estMatCiclo;
        this.materiaInscritas = materiaInscritas;
        this.catedraticoMaterias = catedraticoMaterias;
    }

   
    // Property accessors

    public MateriaCicloId getId() {
        return this.id;
    }
    
    public void setId(MateriaCicloId id) {
        this.id = id;
    }

    public String getEstMatCiclo() {
        return this.estMatCiclo;
    }
    
    public void setEstMatCiclo(String estMatCiclo) {
        this.estMatCiclo = estMatCiclo;
    }

    public Set getMateriaInscritas() {
        return this.materiaInscritas;
    }
    
    public void setMateriaInscritas(Set materiaInscritas) {
        this.materiaInscritas = materiaInscritas;
    }

    public Set getCatedraticoMaterias() {
        return this.catedraticoMaterias;
    }
    
    public void setCatedraticoMaterias(Set catedraticoMaterias) {
        this.catedraticoMaterias = catedraticoMaterias;
    }
   








}