package com.saldei.hibernate.tables;



/**
 * MateriaInscritaId generated by MyEclipse - Hibernate Tools
 */

public class MateriaInscritaId  implements java.io.Serializable {


    // Fields    

     private Estudiante estudiante;
     private MateriaCiclo materiaCiclo;


    // Constructors

    /** default constructor */
    public MateriaInscritaId() {
    }

    
    /** full constructor */
    public MateriaInscritaId(Estudiante estudiante, MateriaCiclo materiaCiclo) {
        this.estudiante = estudiante;
        this.materiaCiclo = materiaCiclo;
    }

   
    // Property accessors

    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }

    public MateriaCiclo getMateriaCiclo() {
        return this.materiaCiclo;
    }
    
    public void setMateriaCiclo(MateriaCiclo materiaCiclo) {
        this.materiaCiclo = materiaCiclo;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MateriaInscritaId) ) return false;
		 MateriaInscritaId castOther = ( MateriaInscritaId ) other; 
         
		 return ( (this.getEstudiante()==castOther.getEstudiante()) || ( this.getEstudiante()!=null && castOther.getEstudiante()!=null && this.getEstudiante().equals(castOther.getEstudiante()) ) )
 && ( (this.getMateriaCiclo()==castOther.getMateriaCiclo()) || ( this.getMateriaCiclo()!=null && castOther.getMateriaCiclo()!=null && this.getMateriaCiclo().equals(castOther.getMateriaCiclo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEstudiante() == null ? 0 : this.getEstudiante().hashCode() );
         result = 37 * result + ( getMateriaCiclo() == null ? 0 : this.getMateriaCiclo().hashCode() );
         return result;
   }   





}