package com.saldei.hibernate.tables;



/**
 * Parametro generated by MyEclipse - Hibernate Tools
 */

public class Parametro  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idParametro;
     private String nomParametro;
     private String descripcion;
     private String valor;


    // Constructors

    /** default constructor */
    public Parametro() {
    }

    
    /** full constructor */
    public Parametro(Integer idParametro, String nomParametro, String descripcion, String valor) {
        this.idParametro = idParametro;
        this.nomParametro = nomParametro;
        this.descripcion = descripcion;
        this.valor = valor;
    }

   
    // Property accessors

    public Integer getIdParametro() {
        return this.idParametro;
    }
    
    public void setIdParametro(Integer idParametro) {
        this.idParametro = idParametro;
    }

    public String getNomParametro() {
        return this.nomParametro;
    }
    
    public void setNomParametro(String nomParametro) {
        this.nomParametro = nomParametro;
    }

    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }
   








}