package com.saldei.hibernate.tables;



/**
 * SeccionXMateriaId generated by MyEclipse - Hibernate Tools
 */

public class SeccionXMateriaId  implements java.io.Serializable {


    // Fields    
	private static final long serialVersionUID = 1L;
     private Materia materia;
     private Integer idSeccion;


    // Constructors

    /** default constructor */
    public SeccionXMateriaId() {
    }

    
    /** full constructor */
    public SeccionXMateriaId(Materia materia, Integer idSeccion) {
        this.materia = materia;
        this.idSeccion = idSeccion;
    }

   
    // Property accessors

    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }

    public Integer getIdSeccion() {
        return this.idSeccion;
    }
    
    public void setIdSeccion(Integer idSeccion) {
        this.idSeccion = idSeccion;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SeccionXMateriaId) ) return false;
		 SeccionXMateriaId castOther = ( SeccionXMateriaId ) other; 
         
		 return ( (this.getMateria()==castOther.getMateria()) || ( this.getMateria()!=null && castOther.getMateria()!=null && this.getMateria().equals(castOther.getMateria()) ) )
 && ( (this.getIdSeccion()==castOther.getIdSeccion()) || ( this.getIdSeccion()!=null && castOther.getIdSeccion()!=null && this.getIdSeccion().equals(castOther.getIdSeccion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMateria() == null ? 0 : this.getMateria().hashCode() );
         result = 37 * result + ( getIdSeccion() == null ? 0 : this.getIdSeccion().hashCode() );
         return result;
   }   





}