package com.saldei.hibernate.tables;

import java.util.HashSet;
import java.util.Set;


/**
 * TipoMedida generated by MyEclipse - Hibernate Tools
 */

public class TipoMedida  implements java.io.Serializable {


    // Fields    

     private Integer idTipoMedida;
     private String nomTipoMedida;
     private String estTipoMedida;
     private Set medidas = new HashSet(0);


    // Constructors

    /** default constructor */
    public TipoMedida() {
    }

	/** minimal constructor */
    public TipoMedida(Integer idTipoMedida, String nomTipoMedida, String estTipoMedida) {
        this.idTipoMedida = idTipoMedida;
        this.nomTipoMedida = nomTipoMedida;
        this.estTipoMedida = estTipoMedida;
    }
    
    /** full constructor */
    public TipoMedida(Integer idTipoMedida, String nomTipoMedida, String estTipoMedida, Set medidas) {
        this.idTipoMedida = idTipoMedida;
        this.nomTipoMedida = nomTipoMedida;
        this.estTipoMedida = estTipoMedida;
        this.medidas = medidas;
    }

   
    // Property accessors

    public Integer getIdTipoMedida() {
        return this.idTipoMedida;
    }
    
    public void setIdTipoMedida(Integer idTipoMedida) {
        this.idTipoMedida = idTipoMedida;
    }

    public String getNomTipoMedida() {
        return this.nomTipoMedida;
    }
    
    public void setNomTipoMedida(String nomTipoMedida) {
        this.nomTipoMedida = nomTipoMedida;
    }

    public String getEstTipoMedida() {
        return this.estTipoMedida;
    }
    
    public void setEstTipoMedida(String estTipoMedida) {
        this.estTipoMedida = estTipoMedida;
    }

    public Set getMedidas() {
        return this.medidas;
    }
    
    public void setMedidas(Set medidas) {
        this.medidas = medidas;
    }
   








}