package com.saldei.hibernate.tables;



/**
 * UsuarioDei generated by MyEclipse - Hibernate Tools
 */

public class UsuarioDei  implements java.io.Serializable {


    // Fields    

     private String codigoEmpleado;
     private Usuario usuario;
     private String extensionUca;


    // Constructors

    /** default constructor */
    public UsuarioDei() {
    }

	/** minimal constructor */
    public UsuarioDei(String codigoEmpleado, Usuario usuario) {
        this.codigoEmpleado = codigoEmpleado;
        this.usuario = usuario;
    }
    
    /** full constructor */
    public UsuarioDei(String codigoEmpleado, Usuario usuario, String extensionUca) {
        this.codigoEmpleado = codigoEmpleado;
        this.usuario = usuario;
        this.extensionUca = extensionUca;
    }

   
    // Property accessors

    public String getCodigoEmpleado() {
        return this.codigoEmpleado;
    }
    
    public void setCodigoEmpleado(String codigoEmpleado) {
        this.codigoEmpleado = codigoEmpleado;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public String getExtensionUca() {
        return this.extensionUca;
    }
    
    public void setExtensionUca(String extensionUca) {
        this.extensionUca = extensionUca;
    }
   








}