/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.saldei.web.action.activos;

import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessages;

import com.saldei.hibernate.tables.activos.ActSolicitudDAO;
import com.saldei.util.hibernate.dao.HibernateSessionFactory;
import com.saldei.web.action.BaseAction;
import com.saldei.web.form.activos.AprSolSuministroForm;

/**
 * MyEclipse Struts Creation date: 07-06-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/aprSolSuministroAction" name="aprSolSuministroForm"
 *                input="/html/activos/aprSolSuministro.jsp" parameter="accion"
 *                scope="request"
 * @struts.action-forward name="succes"
 *                        path="/html/activos/aprSolSuministro.jsp?accion="
 * @struts.action-forward name="back"
 *                        path="/aprSolSuministroAction.do?accion=Find"
 * @struts.action-forward name="updateFail"
 *                        path="/html/activos/aprSolSuministro.jsp"
 */
public class AprSolSuministroAction extends BaseAction {

	@Override
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public ActionForward insert(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public ActionForward update(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub
		return null;
	}

	public ActionForward find(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception, ServletException {
		String solicitante, codSolicitante;
		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;
		List data;

		AprSolSuministroForm aprSolSuministroForm = (AprSolSuministroForm) form;
		ActSolicitudDAO actSolicitudDAO = new ActSolicitudDAO();

		codSolicitante = (String) session.getAttribute("user");
		try {

			/*
			 * if(recibirDescargaActivoForm.getMostrarHistorico()!=null &&
			 * recibirDescargaActivoForm.getMostrarHistorico().equals("S")) data =
			 * actSolicitudDAO.recDescActfindSolicitudes(session.getAttribute("user").toString(),"S");
			 * else data =
			 * actSolicitudDAO.recDescActfindSolicitudes(session.getAttribute("user").toString(),"N");
			 * request.setAttribute("listaSolicitudes", data);
			 */
			if (aprSolSuministroForm.getMostrarHistorico() != null
					&& aprSolSuministroForm.getMostrarHistorico().equals("S"))
				data = actSolicitudDAO.findAllSum("S");
			else
				data = actSolicitudDAO.findAllSum("N");

			request.setAttribute("listSolicitud", data);
			if (!isFLAG_UPDATE()) {
				aprSolSuministroForm.reset(mapping, request);
			} else {
				setFLAG_UPDATE(false);
			}

		} catch (Exception e) {
			e.printStackTrace();
			// TODO: handle exception
		} finally {
			HibernateSessionFactory.getSession().close();
		}
		return mapping.findForward(target);
	}

}