/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.saldei.web.action.activos;

import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessages;

import com.saldei.hibernate.tables.activos.ActSolicitudDAO;
import com.saldei.util.hibernate.dao.HibernateSessionFactory;
import com.saldei.web.action.BaseAction;
import com.saldei.web.form.activos.AprSolDescActForm;

/**
 * MyEclipse Struts Creation date: 06-28-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/aprSolDescActAction" name="aprSolDescActForm"
 *                input="/html/activos/aprSolDescAct.jsp" parameter="accion"
 *                scope="request"
 * @struts.action-forward name="updateFail"
 *                        path="/html/activos/aprSolDescAct.jsp"
 * @struts.action-forward name="back" path="/aprSolDescActAction.do?accion=Find"
 * @struts.action-forward name="success"
 *                        path="/html/activos/aprSolDescAct.jsp?accion="
 */
public class AprSolDescActAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@Override
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public ActionForward insert(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public ActionForward update(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub
		return null;
	}

	public ActionForward find(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception, ServletException {
		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;
		String cod;
		List data;

		AprSolDescActForm aprSolDescActForm = (AprSolDescActForm) form;
		ActSolicitudDAO actSolicitudDAO = new ActSolicitudDAO();
		cod = (String) session.getAttribute("user");
		try {
			/*
			 * if(aprSolCompraForm.getMostrarHistorico()!=null &&
			 * aprSolCompraForm.getMostrarHistorico().equals("S")) data =
			 * actSolicitudDAO.findAllSolicutudComprasEnviadas("S"); else data =
			 * actSolicitudDAO.findAllSolicutudComprasEnviadas("N");
			 * request.setAttribute("listSolComprasEnviadas", data);
			 */

			if (aprSolDescActForm.getMostrarHistorico() != null
					&& aprSolDescActForm.getMostrarHistorico().equals("S"))
				data = actSolicitudDAO.findAprSolDescAct("S");
			else
				data = actSolicitudDAO.findAprSolDescAct("N");
			request.setAttribute("listSolDesc", data);
			if (!isFLAG_UPDATE()) {
				aprSolDescActForm.reset(mapping, request);
			} else {
				setFLAG_UPDATE(false);
			}

		} catch (Exception e) {
			e.printStackTrace();
			// TODO: handle exception
		} finally {
			HibernateSessionFactory.getSession().close();
		}
		return mapping.findForward(target);
	}
}