/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.saldei.web.action.activos;

import java.io.File;
import java.io.FileOutputStream;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessages;

import com.saldei.hibernate.tables.activos.ActCotizacion;
import com.saldei.hibernate.tables.activos.ActCotizacionDAO;
import com.saldei.hibernate.tables.activos.ActSolicitud;
import com.saldei.hibernate.tables.activos.ActSolicitudDAO;
import com.saldei.util.hibernate.dao.HibernateSessionFactory;
import com.saldei.web.action.BaseAction;
import com.saldei.web.form.activos.CotizacionForm;

/**
 * MyEclipse Struts Creation date: 07-01-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/cotizacionAction" name="cotizacionForm"
 *                input="/hmtl/activos/cotizacion.jsp" parameter="accion"
 *                scope="request"
 * @struts.action-forward name="back" path="/cotizacionAction.do?accion=Find"
 * @struts.action-forward name="updateFail" path="/hmtl/activos/cotizacion.jsp"
 * @struts.action-forward name="success"
 *                        path="/hmtl/activos/cotizacion.jsp?accion="
 */
public class CotizacionAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward find(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		CotizacionForm cotizacionForm = (CotizacionForm) form;// TODO
																// Auto-generated
																// method stub
		ActCotizacionDAO actCotizacionDAO = new ActCotizacionDAO();
		ActSolicitudDAO actSolicitudDAO = new ActSolicitudDAO();
		ActSolicitud actSolicitud;

		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;
		List data;

		try {
			/* para guardar la configuracion del grid papa */
			request.setAttribute("numeroPagina", request
					.getParameter("numeroPagina"));
			request.setAttribute("nombreGrid", request
					.getParameter("nombreGrid"));
			request.setAttribute("cantidadPagina", request
					.getParameter("cantidadPagina"));

			data = actCotizacionDAO.findAll(cotizacionForm.getTipoSolicitud(),
					cotizacionForm.getCodSolicitud());
			request.setAttribute("listCotizaciones", data);
			if (!isFLAG_UPDATE()) {
				actSolicitud = actSolicitudDAO.findById(cotizacionForm.getId()
						.getActSolicitud().getId());
				cotizacionForm.reset(mapping, request);
				cotizacionForm.getId().setActSolicitud(actSolicitud);
			} else {
				setFLAG_UPDATE(false);
			}

		} catch (Exception e) {
			e.printStackTrace();
			// TODO: handle exception
		} finally {
			HibernateSessionFactory.getSession().close();
		}
		return mapping.findForward(target);
	}

	@Override
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		CotizacionForm cotizacionForm = (CotizacionForm) form;// TODO
																// Auto-generated
																// method stub
		ActCotizacionDAO actCotizacionDAO = new ActCotizacionDAO();

		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;

		try {
			cotizacionForm.validate(mapping, request, errors);
			if (errors.isEmpty()) {
				actCotizacionDAO.delete(cotizacionForm.getActCotizacion());

				HibernateSessionFactory.getSession().beginTransaction()
						.commit();
				errors.add("cotizacion.mensaje.exito", new ActionError(
						"cotizacion.mensaje.exito.delete"));
			} else {
				target = "updateFail";
				setFLAG_UPDATE(true);
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			HibernateSessionFactory.getSession().beginTransaction().rollback();
		} finally {
			HibernateSessionFactory.getSession().close();
		}

		find(mapping, form, request, response);
		return mapping.findForward(target);
	}

	@Override
	public ActionForward insert(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		CotizacionForm cotizacionForm = (CotizacionForm) form;// TODO
																// Auto-generated
																// method stub
		ActCotizacionDAO actCotizacionDAO = new ActCotizacionDAO();

		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;

		try {
			cotizacionForm.validate(mapping, request, errors);
			if (errors.isEmpty()) {
				// se crea la cotizacion con estado C de creada
				cotizacionForm.getActCotizacion().setEstado("C");

				String fname = cotizacionForm.getArchivoPDF().getFileName();
				if (fname != null && !fname.equals("")) {
					String Directorio = this.getServlet().getServletContext()
							.getRealPath("cotizacionPDFS/");
					String filePath = "cotizacionPDFS/"
							+ cotizacionForm.getCodSolicitud()
							+ cotizacionForm.getCodCotizacion() + fname;
					cotizacionForm.setUrlCotizacion(filePath);
				}
				actCotizacionDAO.save(cotizacionForm.getActCotizacion());
				if (fname != null && !fname.equals("")) {
					this.upLoad(mapping, form, request, response);
				}
				HibernateSessionFactory.getSession().beginTransaction()
						.commit();
				errors.add("cotizacion.mensaje.exito", new ActionError(
						"cotizacion.mensaje.exito.insert"));
			} else {
				setFLAG_UPDATE(true);
			}
		} catch (Exception e) {
			e.printStackTrace();
			HibernateSessionFactory.getSession().beginTransaction().rollback();
			// TODO: handle exception
		} finally {
			HibernateSessionFactory.getSession().close();
		}

		find(mapping, form, request, response);
		return mapping.findForward(target);
	}

	@Override
	public ActionForward update(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		CotizacionForm cotizacionForm = (CotizacionForm) form;// TODO
																// Auto-generated
																// method stub
		ActCotizacionDAO actCotizacionDAO = new ActCotizacionDAO();
		ActCotizacion actCotizacion;

		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;

		try {
			cotizacionForm.validate(mapping, request, errors);
			if (errors.isEmpty()) {
				actCotizacion = actCotizacionDAO.findById(cotizacionForm
						.getActCotizacion().getId());
				actCotizacion.setComentario(cotizacionForm.getComentario());

				String fname = cotizacionForm.getArchivoPDF().getFileName();
				if (fname != null && !fname.equals("")) {
					String Directorio = this.getServlet().getServletContext()
							.getRealPath("cotizacionPDFS/");
					String filePath = "cotizacionPDFS/"
							+ cotizacionForm.getCodSolicitud()
							+ cotizacionForm.getCodCotizacion() + fname;
					actCotizacion.setUrlCotizacion(filePath);
				}

				actCotizacionDAO.merge(cotizacionForm.getActCotizacion());
				HibernateSessionFactory.getSession().beginTransaction()
						.commit();
				if (fname != null && !fname.equals("")) {
					this.upLoad(mapping, form, request, response);
				}
				errors.add("cotizacion.mensaje.exito", new ActionError(
						"cotizacion.mensaje.exito.update"));
			} else {
				target = "updateFail";
				setFLAG_UPDATE(true);
			}
		} catch (Exception e) {
			e.printStackTrace();
			HibernateSessionFactory.getSession().beginTransaction().rollback();
			// TODO: handle exception
		} finally {
			HibernateSessionFactory.getSession().close();
		}

		find(mapping, form, request, response);
		return mapping.findForward(target);
	}

	public ActionForward back(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception, ServletException {

		CotizacionForm a = (CotizacionForm) form;
		// form.reset(mapping,request);

		request.setAttribute("flagBack", "lnk"
				+ String.valueOf(a.getCodSolicitud()));
		return mapping.findForward(KEY_BACK);
	}

	public ActionForward upLoad(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception, ServletException {

		CotizacionForm cotizacion = (CotizacionForm) form;
		// form.reset(mapping,request);

		String url = "";
		String Directorio = this.getServlet().getServletContext().getRealPath(
				"cotizacionPDFS/");

		long size = cotizacion.getArchivoPDF().getFileSize();

		CreateFolder(Directorio);

		String fname = cotizacion.getArchivoPDF().getFileName();
		String ext = fname.substring(fname.lastIndexOf("."));
		if (ext.trim().toLowerCase().equals(".pdf")) {
			/* obtenemos el archivo y lo almacenamos al servidor */
			String contentType = cotizacion.getArchivoPDF().getContentType();
			/*
			 * String fileName = codcur + "-" + typedoc + "-" +
			 * f.getFile().getFileName();
			 */
			String fileName;

			// long size = f.getFile().getFileSize();

			// String filePath =
			// servlet.getServletContext().getRealPath("\\DigitRATS\\"+url);
			String filePath = Directorio + "/" + cotizacion.getCodSolicitud()
					+ cotizacion.getCodCotizacion() + fname;

			byte[] dataArchivo = cotizacion.getArchivoPDF().getFileData();
			cotizacion.getArchivoPDF().destroy();

			/* Creando flujos para almacenar fisicamente el arhivo */
			FileOutputStream newFile = new FileOutputStream(filePath);
			newFile.write(dataArchivo); // escribo los bites del archivo que se
										// subio a un archivo físico
			/* cerrando los flujos */
			newFile.close();

			// Verificando que el archivo guardado mantenga su integradad con el
			// ingresado
			File uploadedFile = new File(filePath);

			if (uploadedFile.length() != size) {
				DeleteFile(filePath);
				// errors.add("ext",new ActionError("file.problem.error"));
			}
		}
		return mapping.findForward("success");
	}

	public static void CreateFolder(String folder) {
		boolean flag = true;
		try {
			File f = new File(folder);
			if (!f.exists() && (!f.isFile())) {
				f.mkdirs();
				flag = true;
			}
			f = null;
		} catch (Exception e) {
			System.out.println("Error: " + e);
		}
	}

	public static void DeleteFile(String url) {
		try {
			File f = new File(url);
			f.delete();
		} catch (Exception e) {
			System.out.println("Error: " + e);
		}
	}

}