/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.saldei.web.action.activos;

import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessages;
import org.hibernate.exception.ConstraintViolationException;

import com.saldei.hibernate.tables.activos.ActEstadoActivoDAO;
import com.saldei.util.hibernate.dao.HibernateSessionFactory;
import com.saldei.web.action.BaseAction;
import com.saldei.web.form.activos.EstadoActivoForm;

/**
 * MyEclipse Struts Creation date: 07-14-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/estadoActivoAction" name="estadoActivoForm"
 *                input="/html/activos/estadoActivo.jsp" parameter="accion"
 *                scope="request"
 * @struts.action-forward name="updateFail"
 *                        path="/html/activos/estadoActivo.jsp"
 * @struts.action-forward name="back"
 *                        path="/estadoActivoAction.do?accion=Regresar"
 * @struts.action-forward name="success"
 *                        path="/html/activos/estadoActivo.jsp?accion="
 */
public class EstadoActivoAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub
		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;

		EstadoActivoForm estadoActivoForm = (EstadoActivoForm) form;
		ActEstadoActivoDAO actEstadoActivoDAO = new ActEstadoActivoDAO();

		try {
			estadoActivoForm.validate(mapping, request, errors);
			if (errors.isEmpty()) {
				actEstadoActivoDAO
						.delete(estadoActivoForm.getActEstadoActivo());
				HibernateSessionFactory.getSession().beginTransaction()
						.commit();
				errors.add("estadoAct.mensaje.exito", new ActionError(
						"estadoAct.mensaje.exito.delete"));
			} else {
				target = "updateFail";
				setFLAG_UPDATE(true);
			}
		} catch (ConstraintViolationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			errors.add("estadoAct.mensajeError.error", new ActionError(
					"estadoAct.mensajeError.error.nodelete"));
			HibernateSessionFactory.getSession().beginTransaction().rollback();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			HibernateSessionFactory.getSession().beginTransaction().rollback();
		} finally {
			HibernateSessionFactory.getSession().close();
		}

		find(mapping, form, request, response);
		return mapping.findForward(target);
	}

	@SuppressWarnings("deprecation")
	public ActionForward insert(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub

		EstadoActivoForm estadoActivoForm = (EstadoActivoForm) form;
		ActEstadoActivoDAO actEstadoActivoDAO = new ActEstadoActivoDAO();

		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;

		try {
			estadoActivoForm.validate(mapping, request, errors);
			if (errors.isEmpty()) {
				actEstadoActivoDAO.save(estadoActivoForm.getActEstadoActivo());
				HibernateSessionFactory.getSession().beginTransaction()
						.commit();
				errors.add("estadoAct.mensaje.exito", new ActionError(
						"estadoAct.mensaje.exito.insert"));
			} else {
				setFLAG_UPDATE(true);
			}
		} catch (Exception e) {
			e.printStackTrace();
			HibernateSessionFactory.getSession().beginTransaction().rollback();
			// TODO: handle exception
		} finally {
			HibernateSessionFactory.getSession().close();
		}

		find(mapping, form, request, response);
		return mapping.findForward(target);
	}

	@SuppressWarnings("deprecation")
	public ActionForward update(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub

		EstadoActivoForm estadoActivoForm = (EstadoActivoForm) form;
		ActEstadoActivoDAO actEstadoActivoDAO = new ActEstadoActivoDAO();

		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;

		try {
			estadoActivoForm.validate(mapping, request, errors);
			if (errors.isEmpty()) {
				actEstadoActivoDAO.merge(estadoActivoForm.getActEstadoActivo());
				HibernateSessionFactory.getSession().beginTransaction()
						.commit();
				errors.add("estadoAct.mensaje.exito", new ActionError(
						"estadoAct.mensaje.exito.modi"));
			} else {
				target = "updateFail";
				setFLAG_UPDATE(true);
			}
		} catch (Exception e) {
			e.printStackTrace();
			HibernateSessionFactory.getSession().beginTransaction().rollback();
			// TODO: handle exception
		} finally {
			HibernateSessionFactory.getSession().close();
		}

		find(mapping, form, request, response);
		return mapping.findForward(target);
	}

	public ActionForward find(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception, ServletException {
		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;
		List data;

		EstadoActivoForm estadoActivoForm = (EstadoActivoForm) form;
		ActEstadoActivoDAO actEstadoActivoDAO = new ActEstadoActivoDAO();

		try {

			data = actEstadoActivoDAO.findAll();
			request.setAttribute("listaEstadoActivo", data);

			// TipoUnidadForm f = (TipoUnidadForm) listaTipoUnidad;
			// unidadForm.setActTipoUnidad(f);

			if (!isFLAG_UPDATE()) {
				estadoActivoForm.reset(mapping, request);
			} else {
				setFLAG_UPDATE(false);
			}

		} catch (Exception e) {
			e.printStackTrace();
			// TODO: handle exception
		} finally {
			HibernateSessionFactory.getSession().close();
		}
		return mapping.findForward(target);
	}

}