/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.saldei.web.action.activos;

import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessages;
import org.hibernate.exception.ConstraintViolationException;

import com.saldei.hibernate.tables.activos.ActProveedorDAO;

import com.saldei.util.hibernate.dao.HibernateSessionFactory;
import com.saldei.web.action.BaseAction;

import com.saldei.web.form.activos.ProveedorForm;

/**
 * MyEclipse Struts Creation date: 05-25-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/proveedorAction" name="proveedorForm"
 *                input="/html/activos/proveedor.jsp" parameter="accion"
 *                scope="request" validate="true"
 * @struts.action-forward name="success" path="/html/activos/proveedor.jsp"
 * @struts.action-forward name="fail" path="/html/activos/proveedor.jsp"
 */
public class ProveedorAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub
		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;

		ProveedorForm proveedorForm = (ProveedorForm) form;
		ActProveedorDAO actProveedorDAO = new ActProveedorDAO();

		try {
			proveedorForm.validate(mapping, request, errors);
			if (errors.isEmpty()) {
				actProveedorDAO.delete(proveedorForm.getActProveedor());
				HibernateSessionFactory.getSession().beginTransaction()
						.commit();
				errors.add("proveedor.mensaje.exito", new ActionError(
						"proveedor.mensaje.exito.delete"));
			} else {
				target = "updateFail";
				setFLAG_UPDATE(true);
			}

		} catch (ConstraintViolationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			errors.add("proveedor.mensajeError.error", new ActionError(
					"proveedor.mensajeError.error.nodelete"));
			HibernateSessionFactory.getSession().beginTransaction().rollback();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			HibernateSessionFactory.getSession().beginTransaction().rollback();
		} finally {
			HibernateSessionFactory.getSession().close();
		}

		find(mapping, form, request, response);
		return mapping.findForward(target);
	}

	@SuppressWarnings("deprecation")
	public ActionForward insert(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub

		ProveedorForm proveedorForm = (ProveedorForm) form;
		ActProveedorDAO actProveedorDAO = new ActProveedorDAO();

		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;

		try {
			proveedorForm.validate(mapping, request, errors);
			if (errors.isEmpty()) {
				actProveedorDAO.save(proveedorForm.getActProveedor());
				HibernateSessionFactory.getSession().beginTransaction()
						.commit();
				errors.add("proveedor.mensaje.exito", new ActionError(
						"proveedor.mensaje.exito.insert"));
			} else {
				setFLAG_UPDATE(true);
			}
		}

		catch (Exception e) {
			e.printStackTrace();
			HibernateSessionFactory.getSession().beginTransaction().rollback();
			// TODO: handle exception
		} finally {
			HibernateSessionFactory.getSession().close();
		}

		find(mapping, form, request, response);
		return mapping.findForward(target);
	}

	public ActionForward update(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub
		ProveedorForm proveedorForm = (ProveedorForm) form;
		ActProveedorDAO actProveedorDAO = new ActProveedorDAO();

		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;

		try {
			proveedorForm.validate(mapping, request, errors);
			if (errors.isEmpty()) {
				actProveedorDAO.merge(proveedorForm.getActProveedor());
				HibernateSessionFactory.getSession().beginTransaction()
						.commit();
				errors.add("proveedor.mensaje.exito", new ActionError(
						"proveedor.mensaje.exito.update"));
			} else {
				target = "updateFail";
				setFLAG_UPDATE(true);
			}
		} catch (Exception e) {
			e.printStackTrace();
			HibernateSessionFactory.getSession().beginTransaction().rollback();
			// TODO: handle exception
		} finally {
			HibernateSessionFactory.getSession().close();
		}

		find(mapping, form, request, response);
		return mapping.findForward(target);
	}

	public ActionForward find(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception, ServletException {
		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;
		List data;

		ProveedorForm proveedorForm = (ProveedorForm) form;
		ActProveedorDAO actProveedorDAO = new ActProveedorDAO();

		try {

			data = actProveedorDAO.findAll();
			request.setAttribute("listaProveedor", data);
			if (!isFLAG_UPDATE()) {
				proveedorForm.reset(mapping, request);
			} else {
				setFLAG_UPDATE(false);
			}

		} catch (Exception e) {
			e.printStackTrace();
			// TODO: handle exception
		} finally {
			HibernateSessionFactory.getSession().close();
		}
		return mapping.findForward(target);
	}

}