/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.saldei.web.action.activos;

import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessages;

import org.hibernate.exception.ConstraintViolationException;

import com.saldei.hibernate.tables.activos.ActSolicitud;
import com.saldei.hibernate.tables.activos.ActSolicitudDAO;
import com.saldei.util.hibernate.dao.HibernateSessionFactory;
import com.saldei.web.action.BaseAction;
import com.saldei.web.form.activos.SolSuministroForm;

/**
 * MyEclipse Struts Creation date: 06-16-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/reqRecursoAction" name="reqRecursoForm"
 *                input="/html/activos/reqRecurso.jsp" parameter="accion"
 *                scope="request"
 * @struts.action-forward name="back" path="/reqRecursoAction.do?accion=Find"
 * @struts.action-forward name="updateFail" path="/html/activos/reqRecurso.jsp"
 * @struts.action-forward name="success"
 *                        path="/html/activos/reqRecurso.jsp?accion="
 */
public class SolSuministroAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@Override
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub
		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;

		SolSuministroForm solSuministroForm = (SolSuministroForm) form;
		ActSolicitudDAO actSolicitudDAO = new ActSolicitudDAO();

		try {
			solSuministroForm.validate(mapping, request, errors);
			if (errors.isEmpty()) {
				actSolicitudDAO.delete(solSuministroForm.getActSolicitud());

				HibernateSessionFactory.getSession().beginTransaction()
						.commit();
				errors.add("suministro.mensaje.exito", new ActionError(
						"suministro.mensaje.exito.delete"));
			} else {
				target = "updateFail";
				setFLAG_UPDATE(true);
			}
		} catch (ConstraintViolationException e) {
			e.printStackTrace();
			errors.add("suministro.mensajeError.error", new ActionError(
					"suministro.mensajeError.error.nodelete"));
			HibernateSessionFactory.getSession().beginTransaction().rollback();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			HibernateSessionFactory.getSession().beginTransaction().rollback();
		} finally {
			HibernateSessionFactory.getSession().close();
		}

		find(mapping, form, request, response);
		return mapping.findForward(target);
	}

	@Override
	public ActionForward insert(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub
		SolSuministroForm solSuministroForm = (SolSuministroForm) form;
		ActSolicitud actSolicitud = new ActSolicitud();
		ActSolicitudDAO actSolicitudDAO = new ActSolicitudDAO();

		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;

		try {
			solSuministroForm.validate(mapping, request, errors);
			if (errors.isEmpty()) {

				if (solSuministroForm.getActSolicitud().getEstado() != "G") {
					solSuministroForm.getActSolicitud().setEstado("G");
				}

				if (solSuministroForm.getActSolicitud().getId()
						.getTipoSolicitud() != "S") {
					solSuministroForm.getActSolicitud().getId()
							.setTipoSolicitud("S");
				}

				actSolicitudDAO.save(solSuministroForm.getActSolicitud());

				HibernateSessionFactory.getSession().beginTransaction()
						.commit();
				errors.add("suministro.mensaje.exito", new ActionError(
						"suministro.mensaje.exito.insert"));
			} else {
				setFLAG_UPDATE(true);
			}
		} catch (Exception e) {
			e.printStackTrace();
			HibernateSessionFactory.getSession().beginTransaction().rollback();
			// TODO: handle exception
		} finally {
			HibernateSessionFactory.getSession().close();
		}

		find(mapping, form, request, response);
		return mapping.findForward(target);
	}

	@Override
	public ActionForward update(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub
		SolSuministroForm solSuministroForm = (SolSuministroForm) form;
		ActSolicitudDAO actSolicitudDAO = new ActSolicitudDAO();
		ActSolicitud actTemp = new ActSolicitud();
		List data2;
		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;

		try {
			solSuministroForm.validate(mapping, request, errors);
			if (errors.isEmpty()) {
				// data2 =
				// actSolicitudDAO.tieneSuministros(solSuministroForm.getCodSolicitud());
				actTemp = actSolicitudDAO.findById(solSuministroForm
						.getActSolicitud().getId());
				solSuministroForm.getActSolicitud().setFechaCreacion(
						actTemp.getFechaCreacion());
				actSolicitudDAO.merge(solSuministroForm.getActSolicitud());
				HibernateSessionFactory.getSession().beginTransaction()
						.commit();
				errors.add("suministro.mensaje.exito", new ActionError(
						"suministro.mensaje.exito.update"));
			} else {
				target = "updateFail";
				setFLAG_UPDATE(true);
			}
		} catch (Exception e) {
			e.printStackTrace();
			HibernateSessionFactory.getSession().beginTransaction().rollback();
			// TODO: handle exception
		} finally {
			HibernateSessionFactory.getSession().close();
		}

		find(mapping, form, request, response);
		return mapping.findForward(target);
	}

	public ActionForward find(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception, ServletException {
		String solicitante, codSolicitante;
		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;
		List data;

		SolSuministroForm solSuministroForm = (SolSuministroForm) form;
		ActSolicitudDAO actSolicitudDAO = new ActSolicitudDAO();

		codSolicitante = (String) session.getAttribute("user");
		try {

			data = actSolicitudDAO.findAllSolSuministro(codSolicitante);

			request.setAttribute("listSolicitud", data);
			if (!isFLAG_UPDATE()) {
				solSuministroForm.reset(mapping, request);
			} else {
				setFLAG_UPDATE(false);
			}

		} catch (Exception e) {
			e.printStackTrace();
			// TODO: handle exception
		} finally {
			HibernateSessionFactory.getSession().close();
		}
		return mapping.findForward(target);
	}
}