package com.saldei.hibernate.tables.activos;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AbstractActUnidad generated by MyEclipse Persistence Tools
 */

public abstract class AbstractActUnidad implements java.io.Serializable {

	// Fields

	private Integer codUnidad;
	private ActTipoUnidad actTipoUnidad;
	private String descripcion;
	private String codResponsable;
	private Date fechaCreacion;
	private String estado;
	private Set actHisResponsableUnidads = new HashSet(0);
	private Set actSolicituds = new HashSet(0);
	private Set actActivos = new HashSet(0);
	private Set actHistUnidadActivos = new HashSet(0);

	// Constructors

	/** default constructor */
	public AbstractActUnidad() {
	}

	/** minimal constructor */
	public AbstractActUnidad(ActTipoUnidad actTipoUnidad, String estado) {
		this.actTipoUnidad = actTipoUnidad;
		this.estado = estado;
	}

	/** full constructor */
	public AbstractActUnidad(ActTipoUnidad actTipoUnidad, String descripcion,
			String codResponsable, Date fechaCreacion, String estado,
			Set actHisResponsableUnidads, Set actSolicituds, Set actActivos,
			Set actHistUnidadActivos) {
		this.actTipoUnidad = actTipoUnidad;
		this.descripcion = descripcion;
		this.codResponsable = codResponsable;
		this.fechaCreacion = fechaCreacion;
		this.estado = estado;
		this.actHisResponsableUnidads = actHisResponsableUnidads;
		this.actSolicituds = actSolicituds;
		this.actActivos = actActivos;
		this.actHistUnidadActivos = actHistUnidadActivos;
	}

	// Property accessors

	public Integer getCodUnidad() {
		return this.codUnidad;
	}

	public void setCodUnidad(Integer codUnidad) {
		this.codUnidad = codUnidad;
	}

	public ActTipoUnidad getActTipoUnidad() {
		return this.actTipoUnidad;
	}

	public void setActTipoUnidad(ActTipoUnidad actTipoUnidad) {
		this.actTipoUnidad = actTipoUnidad;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getCodResponsable() {
		return this.codResponsable;
	}

	public void setCodResponsable(String codResponsable) {
		this.codResponsable = codResponsable;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set getActHisResponsableUnidads() {
		return this.actHisResponsableUnidads;
	}

	public void setActHisResponsableUnidads(Set actHisResponsableUnidads) {
		this.actHisResponsableUnidads = actHisResponsableUnidads;
	}

	public Set getActSolicituds() {
		return this.actSolicituds;
	}

	public void setActSolicituds(Set actSolicituds) {
		this.actSolicituds = actSolicituds;
	}

	public Set getActActivos() {
		return this.actActivos;
	}

	public void setActActivos(Set actActivos) {
		this.actActivos = actActivos;
	}

	public Set getActHistUnidadActivos() {
		return this.actHistUnidadActivos;
	}

	public void setActHistUnidadActivos(Set actHistUnidadActivos) {
		this.actHistUnidadActivos = actHistUnidadActivos;
	}

}