package com.saldei.hibernate.tables.activos;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AbstractActPresupuesto generated by MyEclipse Persistence Tools
 */

public abstract class AbstractActPresupuesto implements java.io.Serializable {

	// Fields

	private Integer codPresupuesto;
	private Date fechaInicial;
	private Date fechaFinal;
	private Date fechaCreacion;
	private String estado;
	private String usuarioMov;
	private Set actDetPresupuestos = new HashSet(0);

	// Constructors

	/** default constructor */
	public AbstractActPresupuesto() {
	}

	/** minimal constructor */
	public AbstractActPresupuesto(String estado) {
		this.estado = estado;
	}

	/** full constructor */
	public AbstractActPresupuesto(Date fechaInicial, Date fechaFinal,
			Date fechaCreacion, String estado, String usuarioMov,
			Set actDetPresupuestos) {
		this.fechaInicial = fechaInicial;
		this.fechaFinal = fechaFinal;
		this.fechaCreacion = fechaCreacion;
		this.estado = estado;
		this.usuarioMov = usuarioMov;
		this.actDetPresupuestos = actDetPresupuestos;
	}

	// Property accessors

	public Integer getCodPresupuesto() {
		return this.codPresupuesto;
	}

	public void setCodPresupuesto(Integer codPresupuesto) {
		this.codPresupuesto = codPresupuesto;
	}

	public Date getFechaInicial() {
		return this.fechaInicial;
	}

	public void setFechaInicial(Date fechaInicial) {
		this.fechaInicial = fechaInicial;
	}

	public Date getFechaFinal() {
		return this.fechaFinal;
	}

	public void setFechaFinal(Date fechaFinal) {
		this.fechaFinal = fechaFinal;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getUsuarioMov() {
		return this.usuarioMov;
	}

	public void setUsuarioMov(String usuarioMov) {
		this.usuarioMov = usuarioMov;
	}

	public Set getActDetPresupuestos() {
		return this.actDetPresupuestos;
	}

	public void setActDetPresupuestos(Set actDetPresupuestos) {
		this.actDetPresupuestos = actDetPresupuestos;
	}

}