package com.saldei.hibernate.tables.activos;

import java.util.Date;

/**
 * AbstractActHistUnidadActivo generated by MyEclipse Persistence Tools
 */

public abstract class AbstractActHistUnidadActivo implements
		java.io.Serializable {

	// Fields

	private Integer correlativo;
	private ActUnidad actUnidad;
	private ActActivo actActivo;
	private Date fechaCreacion;
	private String creadoPor;

	// Constructors

	/** default constructor */
	public AbstractActHistUnidadActivo() {
	}

	/** minimal constructor */
	public AbstractActHistUnidadActivo(Integer correlativo, ActActivo actActivo) {
		this.correlativo = correlativo;
		this.actActivo = actActivo;
	}

	/** full constructor */
	public AbstractActHistUnidadActivo(Integer correlativo,
			ActUnidad actUnidad, ActActivo actActivo, Date fechaCreacion,
			String creadoPor) {
		this.correlativo = correlativo;
		this.actUnidad = actUnidad;
		this.actActivo = actActivo;
		this.fechaCreacion = fechaCreacion;
		this.creadoPor = creadoPor;
	}

	// Property accessors

	public Integer getCorrelativo() {
		return this.correlativo;
	}

	public void setCorrelativo(Integer correlativo) {
		this.correlativo = correlativo;
	}

	public ActUnidad getActUnidad() {
		return this.actUnidad;
	}

	public void setActUnidad(ActUnidad actUnidad) {
		this.actUnidad = actUnidad;
	}

	public ActActivo getActActivo() {
		return this.actActivo;
	}

	public void setActActivo(ActActivo actActivo) {
		this.actActivo = actActivo;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getCreadoPor() {
		return this.creadoPor;
	}

	public void setCreadoPor(String creadoPor) {
		this.creadoPor = creadoPor;
	}

}