package com.saldei.hibernate.tables.activos;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AbstractActCuenta generated by MyEclipse Persistence Tools
 */

public abstract class AbstractActCuenta implements java.io.Serializable {

	// Fields

	private String codCuenta;
	private String descripcion;
	private Date fechaCreacion;
	private Set actDetPresupuestos = new HashSet(0);

	// Constructors

	/** default constructor */
	public AbstractActCuenta() {
	}

	/** minimal constructor */
	public AbstractActCuenta(String codCuenta, String descripcion) {
		this.codCuenta = codCuenta;
		this.descripcion = descripcion;
	}

	/** full constructor */
	public AbstractActCuenta(String codCuenta, String descripcion,
			Date fechaCreacion, Set actDetPresupuestos) {
		this.codCuenta = codCuenta;
		this.descripcion = descripcion;
		this.fechaCreacion = fechaCreacion;
		this.actDetPresupuestos = actDetPresupuestos;
	}

	// Property accessors

	public String getCodCuenta() {
		return this.codCuenta;
	}

	public void setCodCuenta(String codCuenta) {
		this.codCuenta = codCuenta;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Set getActDetPresupuestos() {
		return this.actDetPresupuestos;
	}

	public void setActDetPresupuestos(Set actDetPresupuestos) {
		this.actDetPresupuestos = actDetPresupuestos;
	}

}