package com.saldei.hibernate.tables.activos;

/**
 * AbstractActDetSolicitudId generated by MyEclipse Persistence Tools
 */

public abstract class AbstractActDetSolicitudId implements java.io.Serializable {

	// Fields

	private ActSolicitud actSolicitud;
	private Integer correlativo;

	// Constructors

	/** default constructor */
	public AbstractActDetSolicitudId() {
	}

	/** full constructor */
	public AbstractActDetSolicitudId(ActSolicitud actSolicitud,
			Integer correlativo) {
		this.actSolicitud = actSolicitud;
		this.correlativo = correlativo;
	}

	// Property accessors

	public ActSolicitud getActSolicitud() {
		return this.actSolicitud;
	}

	public void setActSolicitud(ActSolicitud actSolicitud) {
		this.actSolicitud = actSolicitud;
	}

	public Integer getCorrelativo() {
		return this.correlativo;
	}

	public void setCorrelativo(Integer correlativo) {
		this.correlativo = correlativo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AbstractActDetSolicitudId))
			return false;
		AbstractActDetSolicitudId castOther = (AbstractActDetSolicitudId) other;

		return ((this.getActSolicitud() == castOther.getActSolicitud()) || (this
				.getActSolicitud() != null
				&& castOther.getActSolicitud() != null && this
				.getActSolicitud().equals(castOther.getActSolicitud())))
				&& ((this.getCorrelativo() == castOther.getCorrelativo()) || (this
						.getCorrelativo() != null
						&& castOther.getCorrelativo() != null && this
						.getCorrelativo().equals(castOther.getCorrelativo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getActSolicitud() == null ? 0 : this.getActSolicitud()
						.hashCode());
		result = 37
				* result
				+ (getCorrelativo() == null ? 0 : this.getCorrelativo()
						.hashCode());
		return result;
	}

}