package com.saldei.hibernate.tables.activos;

// Generated by MyEclipse Persistence Tools

import java.util.Set;

/**
 * ActCotizacion generated by MyEclipse Persistence Tools
 */
public class ActCotizacion extends AbstractActCotizacion implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public ActCotizacion() {
	}

	/** minimal constructor */
	public ActCotizacion(ActCotizacionId id, ActProveedor actProveedor) {
		super(id, actProveedor);
	}

	

	/**
	 * @param id
	 * @param actProveedor
	 * @param urlCotizacion
	 * @param estado
	 * @param comentario
	 * @param iva
	 * @param actDetCotizacions
	 */
	public ActCotizacion(ActCotizacionId id, ActProveedor actProveedor,
			String urlCotizacion, String estado, String comentario, String iva,
			Set actDetCotizacions) {
		super(id, actProveedor, urlCotizacion, estado, comentario, iva,
				actDetCotizacions);
		// TODO Auto-generated constructor stub
	}

	public String getLink() {
		String link = " <a  href='#' onclick=\"javascript:enviarCotizacion('Find','"
				+ this.getId().getActSolicitud().getId().getTipoSolicitud()
				+ "','"
				+ this.getId().getActSolicitud().getId().getCodSolicitud()
				+ "','"
				+ this.getId().getCodCotizacion()
				+ "');return false;\" >";
		link += " Detalle de cotizaci&oacute;n</a>";

		return link;

	}

	public boolean getDetalleCotizacion() {
		if (this.getActDetCotizacions() != null)
			return this.getActDetCotizacions().isEmpty();
		else
			return true;
	}

}
