package com.saldei.hibernate.tables.activos;

// Generated by MyEclipse Persistence Tools

import java.util.Set;

/**
 * ActMotivoBaja generated by MyEclipse Persistence Tools
 */
public class ActMotivoBaja extends AbstractActMotivoBaja implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public ActMotivoBaja() {
	}

	public ActMotivoBaja(String descripcion, Set actActivos) {
		super(descripcion, actActivos);
		// TODO Auto-generated constructor stub
	}

	/**
	 * @param descripcion
	 */
	public ActMotivoBaja(String descripcion) {
		super(descripcion);
		// TODO Auto-generated constructor stub
	}

}
