package com.saldei.hibernate.tables.activos;

// Generated by MyEclipse Persistence Tools

import java.util.Date;
import java.util.Set;

/**
 * ActUnidad generated by MyEclipse Persistence Tools
 */
public class ActUnidad extends AbstractActUnidad implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public ActUnidad() {
		super.setCodUnidad(null);
	}

	/** minimal constructor */
	public ActUnidad(ActTipoUnidad actTipoUnidad) {
		this.setActTipoUnidad(actTipoUnidad);
	}

	public ActUnidad(ActTipoUnidad actTipoUnidad, String descripcion,
			String codResponsable, Date fechaCreacion, String estado,
			Set actHisResponsableUnidads, Set actSolicituds, Set actActivos,
			Set actHistUnidadActivos) {
		super(actTipoUnidad, descripcion, codResponsable, fechaCreacion,
				estado, actHisResponsableUnidads, actSolicituds, actActivos,
				actHistUnidadActivos);
		// TODO Auto-generated constructor stub
	}

	public ActUnidad(ActTipoUnidad actTipoUnidad, String estado) {
		super(actTipoUnidad, estado);
		// TODO Auto-generated constructor stub
	}

}
