package com.saldei.hibernate.tables.seguridad;

import com.saldei.hibernate.tables.Opcion;

// Generated by MyEclipse Persistence Tools

/**
 * OpcionSeguridad generated by MyEclipse Persistence Tools
 */
public class OpcionSeguridad extends AbstractOpcionSeguridad implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public OpcionSeguridad() {
	}

	/** minimal constructor */
	public OpcionSeguridad(Integer idOpcion, Opcion opcion) {
		super(idOpcion, opcion);
	}

	/** full constructor */
	public OpcionSeguridad(Integer idOpcion, Opcion opcion, String visible) {
		super(idOpcion, opcion, visible);
	}

}
