/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.saldei.web.action.inventario;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessages;

import com.saldei.hibernate.tables.activos.ActDetSolicitudDAO;
import com.saldei.hibernate.tables.activos.ActSolicitud;
import com.saldei.hibernate.tables.activos.ActSolicitudDAO;
import com.saldei.hibernate.tables.inventario.InvBodega;
import com.saldei.hibernate.tables.inventario.InvBodegaDAO;
import com.saldei.hibernate.tables.inventario.InvRecursoDAO;
import com.saldei.util.hibernate.dao.HibernateSessionFactory;
import com.saldei.web.action.BaseAction;
import com.saldei.web.form.inventario.ConsultaBodegaForm;
import com.saldei.web.form.inventario.DetAprSolAbaForm;

/** 
 * MyEclipse Struts
 * Creation date: 07-14-2009
 * 
 * XDoclet definition:
 * @struts.action path="/consultaBodegaAction" name="consultaBodegaForm" input="/html/inventario/consultaBodega.jsp" parameter="accion" scope="request"
 * @struts.action-forward name="updateFail" path="/html/inventario/consultaBodega.jsp"
 * @struts.action-forward name="back" path="/consultaBodegaAction.do?accion=Find"
 * @struts.action-forward name="success" path="/html/inventario/consultaBodega.jsp?accion="
 */
public class ConsultaBodegaAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */


	@Override
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public ActionForward insert(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public ActionForward update(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub
		return null;
	}
	
	
	public ActionForward find(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception,
			ServletException {		
		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;
		List data,data2;
		
		try{
		ConsultaBodegaForm consultaBodegaForm = (ConsultaBodegaForm) form;
		InvRecursoDAO invRecursoDAO = new InvRecursoDAO();
		/*ActDetSolicitudDAO actDetSolicitudDAO = new ActDetSolicitudDAO();
		ActSolicitud actSolicitud = new ActSolicitud();
		ActSolicitudDAO actSolicitudDAO = new ActSolicitudDAO();*/
				
			data = invRecursoDAO.findRecursosxBodega();
			request.setAttribute("listConsultaBodega", data);
		    
			if(!isFLAG_UPDATE()){
				consultaBodegaForm .reset(mapping, request);
			}else{
				setFLAG_UPDATE(false);
			}
			//detallePptoForm.setCodPresupuesto(codppto);
			
		} catch (Exception e) {
			e.printStackTrace();			
			// TODO: handle exception
		}finally{
			HibernateSessionFactory.getSession().close();
		} 	
		return mapping.findForward(target);
	}

}