/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.saldei.web.action.inventario;

import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessages;
import org.hibernate.exception.ConstraintViolationException;

import com.saldei.hibernate.tables.inventario.InvCategoriaDAO;
import com.saldei.hibernate.tables.inventario.InvSubCategoria;
import com.saldei.hibernate.tables.inventario.InvSubCategoriaDAO;
import com.saldei.util.hibernate.dao.HibernateSessionFactory;
import com.saldei.web.action.BaseAction;
import com.saldei.web.form.inventario.CategoriaForm;
import com.saldei.web.form.inventario.SubcategoriaForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-31-2009
 * 
 * XDoclet definition:
 * @struts.action path="/subcategoriaAction" name="subcategoriaForm" input="/hml/inventario/subcategoria.jsp" parameter="accion" scope="request"
 * @struts.action-forward name="back" path="/subcategoriaAction.do?accion=Find"
 * @struts.action-forward name="updateFail" path="/hml/inventario/subcategoria.jsp"
 * @struts.action-forward name="success" path="/hml/inventario/subcategoria.jsp?accion="
 */
public class SubcategoriaAction extends BaseAction {

	@Override
	
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub
		HttpSession session = request.getSession(true);
	    String target = KEY_SUCCESS;
	    
		SubcategoriaForm subcategoriaForm = (SubcategoriaForm) form;
		InvSubCategoriaDAO invSubCategoriaDAO = new InvSubCategoriaDAO();
		try {
			subcategoriaForm.validate(mapping, request, errors);
			if (errors.isEmpty()) {
				invSubCategoriaDAO.delete(subcategoriaForm.getInvSubCategoria());			    
			    HibernateSessionFactory.getSession().beginTransaction().commit();
				errors.add("subcat.mensaje.exito", new ActionError("subcat.mensaje.exito.delete"));
			}else{
				target = "updateFail";
				setFLAG_UPDATE(true);
			}
		}catch (ConstraintViolationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			errors.add("subcat.mensajeError.error", new ActionError("subcat.mensajeError.error.nodelete"));
			HibernateSessionFactory.getSession().beginTransaction().rollback();
		}catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			HibernateSessionFactory.getSession().beginTransaction().rollback();
		}finally{
			HibernateSessionFactory.getSession().close();
		}
		
	    find(mapping, form, request, response);
		return mapping.findForward(target);

	}

	@Override
	public ActionForward insert(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub
		HttpSession session = request.getSession(true);
	    String target = KEY_SUCCESS;
	    
	    SubcategoriaForm subcategoriaForm = (SubcategoriaForm) form;
		InvSubCategoriaDAO invSubCategoriaDAO = new InvSubCategoriaDAO();
		
		try {
			subcategoriaForm.validate(mapping, request, errors);
			if (errors.isEmpty()) {
				if(invSubCategoriaDAO.findById(subcategoriaForm.getId())==null){
					invSubCategoriaDAO.save(subcategoriaForm.getInvSubCategoria());			    
				    HibernateSessionFactory.getSession().beginTransaction().commit();
					errors.add("subcat.mensaje.exito", new ActionError("subcat.mensaje.exito.insert"));
				}
				else
					errors.add("subcat.mensaje.exito", new ActionError("subcat.mensaje.exito.noinsert"));
			}else{
				setFLAG_UPDATE(true);
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			HibernateSessionFactory.getSession().beginTransaction().rollback();
		}finally{
			HibernateSessionFactory.getSession().close();
		}
		
	    find(mapping, form, request, response);
		return mapping.findForward(target);

	}

	@Override
	public ActionForward update(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,
			ActionErrors errors, ActionMessages messages) throws Exception,
			ServletException {
		// TODO Auto-generated method stub
		HttpSession session = request.getSession(true);
	    String target = KEY_SUCCESS;
	    
	    SubcategoriaForm subcategoriaForm = (SubcategoriaForm) form;
		InvSubCategoriaDAO invSubCategoriaDAO = new InvSubCategoriaDAO();
		try {
			subcategoriaForm.validate(mapping, request, errors);
			if (errors.isEmpty()) {
				invSubCategoriaDAO.merge(subcategoriaForm.getInvSubCategoria());			    
			    HibernateSessionFactory.getSession().beginTransaction().commit();
				errors.add("subcat.mensaje.exito", new ActionError("subcat.mensaje.exito.update"));
			}else{
				//target = "updateFail";
				setFLAG_UPDATE(true);
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			HibernateSessionFactory.getSession().beginTransaction().rollback();
		}finally{
			HibernateSessionFactory.getSession().close();
		}
		
	    find(mapping, form, request, response);
		return mapping.findForward(target);
	}
	
	public ActionForward find(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception,
			ServletException {		
		HttpSession session = request.getSession(true);
		String target = KEY_SUCCESS;
		List data;
		
		 SubcategoriaForm subcategoriaForm = (SubcategoriaForm) form;
			InvSubCategoriaDAO invSubCategoriaDAO = new InvSubCategoriaDAO();					
	    
		try {
							
			data = invSubCategoriaDAO.findAll();
		    request.setAttribute("listSubCategoria", data);
			if(!isFLAG_UPDATE()){
				subcategoriaForm.reset(mapping, request);
			}else{
				setFLAG_UPDATE(false);
			}			
			
		} catch (Exception e) {
			e.printStackTrace();			
			// TODO: handle exception
		}finally{
			HibernateSessionFactory.getSession().close();
		} 	
		return mapping.findForward(target);
	}
	
}